// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

namespace Nafadh_Backend.Enums
{
    public enum NFD_UserStatus
    {
        Active, Inactive, Suspended, PendingVerification
    }

    public enum NFD_CompanyStatus
    {
        PendingApproval, Approved, Suspended, Rejected
    }

    public enum NFD_TrainerStatus
    {
        Active, Inactive, Suspended
    }

    public enum NFD_TraineeStatus
    {
        Active, Graduated, Dropped, Suspended
    }

    public enum NFD_TrackStatus
    {
        Active, Archived
    }

    public enum NFD_ProgramStatus
    {
        Draft, Published, Archived
    }

    public enum NFD_BatchStatus
    {
        Upcoming, Ongoing, Completed, Cancelled
    }

    public enum NFD_EnrollmentCompletionStatus
    {
        InProgress, Completed, Dropped, Failed
    }

    public enum NFD_ModuleProgressStatus
    {
        NotStarted, InProgress, Completed
    }

    public enum NFD_SessionStatus
    {
        Scheduled, Completed, Cancelled, Postponed
    }

    public enum NFD_AttendanceStatus
    {
        Present, Absent, Late, Excused
    }

    public enum NFD_ExcuseStatus
    {
        Pending, Approved, Rejected
    }

    public enum NFD_TaskPriority
    {
        Low, Medium, High, Critical
    }

    public enum NFD_TaskStatus
    {
        Open, Closed, Overdue
    }

    public enum NFD_SubmissionStatus
    {
        Submitted, UnderReview, Graded, ReturnedForRevision, Late
    }

    public enum NFD_ProjectStatus
    {
        Planned, InProgress, Completed, Cancelled
    }

    public enum NFD_ProjectMemberRole
    {
        Lead, Contributor
    }

    public enum NFD_EvaluationType
    {
        Technical, Behavioral, CompanyEvaluation, Final, TrainerPerformance
    }

    public enum NFD_EvaluationPeriod
    {
        Weekly, Monthly, Midterm, Final, AdHoc
    }

    public enum NFD_WarningType
    {
        Attendance, Performance, Behavioral, Other
    }

    public enum NFD_WarningLevel
    {
        Low, Medium, High, Critical
    }

    public enum NFD_WarningStatus
    {
        Open, UnderReview, Resolved, Escalated
    }

    public enum NFD_SupportTicketStatus
    {
        Open, InProgress, Resolved, Closed
    }

    public enum NFD_AnnouncementScopeType
    {
        Platform, Company, Batch
    }

    public enum NFD_MessageStatus
    {
        Sent, Delivered, Read
    }

    public enum NFD_CertificateType
    {
        Completion, Recommendation, Excellence
    }

    public enum NFD_ReportType
    {
        Attendance, Performance, Financial, Enrollment, Custom
    }

    public enum NFD_PaymentStatus
    {
        Pending, PartiallyPaid, Paid, Overdue, Cancelled
    }

    public enum NFD_PaymentScheduleStatus
    {
        Pending, Paid, Overdue
    }

    public enum NFD_FileType
    {
        Pdf, Video, Image, Document, Link, Other
    }

    public enum NFD_SupervisorStatus
    {
        Active, Inactive, Suspended
    }
    //
}