// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;
using Nafadh_Backend.Repositories;
using static Nafadh_Backend.DTOs.BatchDTO;

namespace Nafadh_Backend.Services
{
    public class BatchService : IBatchService
    {
        private readonly IBatchRepository _repository;

        public BatchService(IBatchRepository repository)
        {
            _repository = repository;
        }

        public async Task<List<BatchDto>> GetAllAsync(int? programId, string? status, DateTime? from, DateTime? to)
        {
            var batches = await _repository.GetAllAsync(programId, status, from, to);
            return batches.Select(MapToDto).ToList();
        }

        public async Task<BatchDto?> GetByIdAsync(int id)
        {
            var batch = await _repository.GetByIdAsync(id);
            return batch == null ? null : MapToDto(batch);
        }

        public async Task<BatchDto> CreateAsync(CreateBatchDto dto)
        {
            var entity = new NFD_Batch
            {
                ProgramId = dto.ProgramId,
                BatchName = dto.BatchName,
                StartDate = dto.StartDate,
                EndDate = dto.EndDate,
                Capacity = dto.Capacity,
                Status = NFD_BatchStatus.Upcoming
            };

            var created = await _repository.AddAsync(entity);
            return MapToDto(created);
        }

        public async Task<bool> UpdateAsync(int id, UpdateBatchDto dto)
        {
            var batch = await _repository.GetByIdAsync(id);
            if (batch == null) return false;

            batch.StartDate = dto.StartDate;
            batch.EndDate = dto.EndDate;
            batch.Capacity = dto.Capacity;
            batch.Status = dto.Status;

            await _repository.UpdateAsync(batch);
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var batch = await _repository.GetByIdAsync(id);
            if (batch == null) return false;

            // Soft-cancel instead of hard delete
            batch.Status = NFD_BatchStatus.Cancelled;
            await _repository.UpdateAsync(batch);
            return true;
        }

        public async Task<List<BatchTraineeDto>> GetTraineesAsync(int batchId)
        {
            // Placeholder: Roster comes from NFD_Enrollments (Widdad's scope)
            return await Task.FromResult(new List<BatchTraineeDto>());
        }

        public async Task<BatchCapacityDto?> GetCapacityAsync(int batchId)
        {
            var batch = await _repository.GetByIdAsync(batchId);
            if (batch == null) return null;

            int enrolledCount = 0; // Placeholder until Enrollment repo is connected

            return new BatchCapacityDto
            {
                BatchId = batch.BatchId,
                Capacity = batch.Capacity,
                EnrolledCount = enrolledCount
            };
        }

        private static BatchDto MapToDto(NFD_Batch b) => new BatchDto
        {
            BatchId = b.BatchId,
            ProgramId = b.ProgramId,
            BatchName = b.BatchName,
            StartDate = b.StartDate,
            EndDate = b.EndDate,
            Capacity = b.Capacity,
            Status = b.Status
        };
    }
}
