// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.DTOs;

using Nafadh_Backend.Models;
using Nafadh_Backend.Repositories;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Nafadh_Backend.Services
{
    public class BatchTrainerService : IBatchTrainerService
    {
        private readonly IBatchTrainerRepository _repository;
        private readonly IBatchRepository _batchRepository;
        private readonly ITrainerRepository _trainerRepository;

        public BatchTrainerService(
            IBatchTrainerRepository repository,
            IBatchRepository batchRepository,
            ITrainerRepository trainerRepository)
        {
            _repository = repository;
            _batchRepository = batchRepository;
            _trainerRepository = trainerRepository;
        }

        // =========================================================
        // Get trainers assigned to a batch
        // =========================================================

        public async Task<List<TrainerInBatchDto>> GetTrainersForBatchAsync(int batchId)
        {
            var links = await _repository.GetByBatchIdAsync(batchId);

            var result = new List<TrainerInBatchDto>();

            foreach (var link in links)
            {
                // جلب بيانات المدرب الحقيقية
                var trainer = await _trainerRepository.GetByIdAsync(link.TrainerId);

                result.Add(new TrainerInBatchDto
                {
                    TrainerId = link.TrainerId,

                    TrainerName =
                        trainer?.User?.FullName
                        ?? string.Empty
                });
            }

            return result;
        }


        // =========================================================
        // Get batches assigned to a trainer
        // =========================================================

        public async Task<List<BatchForTrainerDto>> GetBatchesForTrainerAsync(int trainerId)
        {
            // جلب روابط المدرب بالدفعات
            var links = await _repository.GetByTrainerIdAsync(trainerId);

            var result = new List<BatchForTrainerDto>();

            foreach (var link in links)
            {
                // جلب بيانات الدفعة الحقيقية من قاعدة البيانات
                var batch = await _batchRepository.GetByIdAsync(link.BatchId);

                if (batch == null)
                    continue;

                result.Add(new BatchForTrainerDto
                {
                    BatchId = batch.BatchId,

                    BatchName =
                        batch.BatchName
                        ?? string.Empty,

                    StartDate = batch.StartDate,

                    EndDate = batch.EndDate,

                    Status = batch.Status
                });
            }

            return result;
        }


        // =========================================================
        // Assign trainer to batch
        // =========================================================

        public async Task<bool> AssignAsync(AssignTrainerDto dto)
        {
            // منع تكرار إسناد نفس المدرب لنفس الدفعة
            if (await _repository.ExistsAsync(dto.BatchId, dto.TrainerId))
                return false;

            // التأكد من وجود المدرب
            var trainerExists =
                await _trainerRepository.GetByIdAsync(dto.TrainerId) != null;

            // التأكد من وجود الدفعة
            var batchExists =
                await _batchRepository.GetByIdAsync(dto.BatchId) != null;

            if (!trainerExists || !batchExists)
                return false;

            await _repository.AddAsync(
                new NFD_BatchTrainer
                {
                    BatchId = dto.BatchId,
                    TrainerId = dto.TrainerId
                }
            );

            return true;
        }


        // =========================================================
        // Unassign trainer from batch
        // =========================================================

        public async Task<bool> UnassignAsync(UnassignTrainerDto dto)
        {
            return await _repository.DeleteAsync(
                dto.BatchId,
                dto.TrainerId
            );
        }
    }
}