// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using Nafadh_Backend.Models;
using Nafadh_Backend.Repositories;
using Nafadh_Backend.DTOs;

namespace Nafadh_Backend.Services
{
    public class CertificateService : ICertificateService
    {
        private readonly ICertificateRepository _repository;

        public CertificateService(ICertificateRepository repository)
        {
            _repository = repository;
        }

        // TODO: implement business-logic contract methods for this entity

        // GET certificate by enrollment
        public async Task<CertificateOutputDTO?> GetCertificateByEnrollmentIdAsync(int enrollmentId)
        {
            var certificate =
                await _repository.GetCertificateByEnrollmentIdAsync(enrollmentId);


            if (certificate == null)
                return null;


            return new CertificateOutputDTO
            {
                CertificateId = certificate.CertificateId,
                EnrollmentId = certificate.EnrollmentId,
                IssueDate = certificate.IssueDate,
                Type = certificate.Type,
                FileUrl= certificate.FileUrl
            };

        }

        // Create certificate
        public async Task<CertificateOutputDTO> AddCertificateAsync(CertificateInputDTO dto)
        {

            NFD_Certificate certificate = new NFD_Certificate
            {
                Type = dto.Type,
                IssueDate = dto.IssueDate,
                FileUrl = dto.FileUrl,
                EnrollmentId = dto.EnrollmentId
            };


            await _repository.AddCertificateAsync(certificate);


            return new CertificateOutputDTO
            {
                CertificateId = certificate.CertificateId,
                EnrollmentId = certificate.EnrollmentId,
                IssueDate = certificate.IssueDate,
                Type = certificate.Type,
                FileUrl = certificate.FileUrl
            };
        }


        // Download certificate file
        public async Task<string?> DownloadCertificateAsync(int id)
        {
            var certificate = await _repository.GetCertificateByIdAsync(id);

            if (certificate == null)
                return null;

            if (string.IsNullOrEmpty(certificate.FileUrl))
                return null;

            return certificate.FileUrl;
        }

        // Get all certificates for trainee
        public async Task<List<CertificateOutputDTO>> GetCertificatesByTraineeIdAsync(int traineeId)
        {

            var certificates =await _repository.GetCertificatesByTraineeIdAsync(traineeId);


            return certificates.Select(c => new CertificateOutputDTO
            {
                CertificateId = c.CertificateId,
                EnrollmentId = c.EnrollmentId,
                IssueDate = c.IssueDate,
                Type = c.Type,
                FileUrl = c.FileUrl

            }).ToList();

        }

        //============-- Admin portal==========-

        public async Task<List<TraineeCertificateStatusDTO>> GetBatchCertificatesStatusAsync(int batchId)
        {
            return await _repository.GetBatchCertificatesStatusAsync(batchId);
        }

        // isIssued = true  → لو موجودة شهادة يرجّعها كما هي، لو مو موجودة يرجّع null
        //                    (لأن الـ DTO ما فيه Type/FileUrl الكافية لإنشاء شهادة جديدة —
        //                     استخدم POST /api/Certificate للإصدار الفعلي)
        // isIssued = false → سحب/إلغاء الشهادة الموجودة (revoke)
        public async Task<CertificateOutputDTO?> UpdateCertificateStatusAsync(int enrollmentId, bool isIssued)
        {
            var existing = await _repository.GetCertificateByEnrollmentIdAsync(enrollmentId);

            if (!isIssued)
            {
                if (existing == null)
                    return null;

                await _repository.DeleteCertificateByEnrollmentIdAsync(enrollmentId);

                return new CertificateOutputDTO
                {
                    CertificateId = existing.CertificateId,
                    EnrollmentId = enrollmentId,
                    IssueDate = existing.IssueDate,
                    Type = existing.Type,
                    FileUrl = null
                };
            }

            if (existing == null)
                return null; // وجّه المستخدم لاستخدام AddCertificate بدلاً من هذا الـ endpoint

            return new CertificateOutputDTO
            {
                CertificateId = existing.CertificateId,
                EnrollmentId = existing.EnrollmentId,
                IssueDate = existing.IssueDate,
                Type = existing.Type,
                FileUrl = existing.FileUrl
            };
        }


    }
}
