// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.DTOs.CompanyPayment;
using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;
using Nafadh_Backend.Repositories;

namespace Nafadh_Backend.Services
{
    public class CompanyPaymentService : ICompanyPaymentService
    {
        private readonly ICompanyPaymentRepository _repository;

        public CompanyPaymentService(ICompanyPaymentRepository repository)
        {
            _repository = repository;
        }

        public async Task<IEnumerable<CompanyPaymentResponseDto>>
           GetCompanyPaymentsAsync(int companyId)
        {

            var payments =
                await _repository
                .GetByCompanyIdAsync(companyId);



            return payments.Select(p => new CompanyPaymentResponseDto
            {
                CompanyPaymentId = p.CompanyPaymentId,

                TotalAmount = p.TotalAmount,

                Status = p.Status,

                CompanyId = p.CompanyId,

                CompanyName = p.Company.CompanyName,

                BatchId = p.BatchId

            });

        }


        public async Task<CompanyPaymentResponseDto?>
            GetPaymentDetailsAsync(int id)
        {

            var payment =
                await _repository.GetByIdAsync(id);


            if (payment == null)
                return null;



            return new CompanyPaymentResponseDto
            {
                CompanyPaymentId =
                    payment.CompanyPaymentId,

                TotalAmount =
                    payment.TotalAmount,

                Status =
                    payment.Status,

                CompanyId =
                    payment.CompanyId,

                CompanyName =
                    payment.Company.CompanyName,

                BatchId =
                    payment.BatchId,

                PaymentSchedules =
                    payment.CompanyPaymentSchedules
                    .Cast<object>()
                    .ToList()
            };

        }



        public async Task<CompanyPaymentResponseDto>
            CreatePaymentAsync(
                CreateCompanyPaymentDto dto)
        {

            var payment =
                new NFD_CompanyPayment
                {
                    TotalAmount = dto.TotalAmount,

                    CompanyId = dto.CompanyId,

                    BatchId = dto.BatchId,

                    Status =
                    NFD_PaymentStatus.Pending
                };



            await _repository.AddAsync(payment);



            return new CompanyPaymentResponseDto
            {
                CompanyPaymentId =
                    payment.CompanyPaymentId,

                TotalAmount =
                    payment.TotalAmount,

                Status =
                    payment.Status,

                CompanyId =
                    payment.CompanyId,

                BatchId =
                    payment.BatchId
            };

        }


        public async Task<bool> UpdatePaymentStatusAsync(
                 int id,
                UpdateCompanyPaymentStatusDto dto)
        {

            var payment =
                await _repository.GetByIdAsync(id);



            if (payment == null)
                return false;



            payment.Status =
                dto.Status;



            await _repository.UpdateAsync(payment);



            return true;
        }
    }
}