// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;
using Nafadh_Backend.Repositories;

namespace Nafadh_Backend.Services
{
    public class CompanyPaymentService : ICompanyPaymentService
    {
        private readonly ICompanyPaymentRepository _repository;

        public CompanyPaymentService(ICompanyPaymentRepository repository)
        {
            _repository = repository;
        }

        public async Task<IEnumerable<NFD_CompanyPayment>> GetCompanyPaymentsAsync(int companyId)
        {
            return await _repository.GetByCompanyIdAsync(companyId);
        }

        public async Task<NFD_CompanyPayment?> GetPaymentDetailsAsync(int id)
        {
            return await _repository.GetByIdAsync(id);
        }

        public async Task<NFD_CompanyPayment> CreatePaymentAsync(NFD_CompanyPayment payment)
        {
            payment.Status = NFD_PaymentStatus.Pending;

            await _repository.AddAsync(payment);

            return payment;
        }

        public async Task<bool> UpdatePaymentStatusAsync(int id, NFD_PaymentStatus status)
        {
            var payment = await _repository.GetByIdAsync(id);

            if (payment == null)
                return false;

            payment.Status = status;

            await _repository.UpdateAsync(payment);

            return true;
        }
    }
}