// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>
using Nafadh_Backend.DTOs;
using Nafadh_Backend.DTOs.CompanyPayment;
using System.Linq;
using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;
using Nafadh_Backend.Repositories;

namespace Nafadh_Backend.Services
{
    // Service responsible for handling company business logic
    public class CompanyService : ICompanyService
    {
        private readonly ICompanyRepository _repository;

        // Constructor - inject Company Repository
        public CompanyService(ICompanyRepository repository)
        {
            _repository = repository;
        }

        // Get Company by ID
        public async Task<NFD_CompanyOutputDTO?> GetCompanyByIdAsync(int companyId)
        {
            var company = await _repository.GetCompanyByIdAsync(companyId);

            if (company == null)
                return null;

            var links = await _repository.GetEnrollmentLinksAsync();
            return MapToOutputDTO(company, BuildEnrollmentLookup(links));
        }

        // Get all Companies
        public async Task<IEnumerable<NFD_CompanyOutputDTO>> GetAllCompaniesAsync()
        {
            var companies = await _repository.GetAllCompaniesAsync();
            var links = await _repository.GetEnrollmentLinksAsync();
            var lookup = BuildEnrollmentLookup(links);

            return companies.Select(c => MapToOutputDTO(c, lookup));
        }

        // Get Companies filtered by Status and/or Work Field
        public async Task<IEnumerable<NFD_CompanyOutputDTO>> GetCompaniesAsync(
         NFD_CompanyStatus? status,
         string? workField)
        {
            var companies = await _repository.GetCompaniesAsync(
            status,
            workField);

            var links = await _repository.GetEnrollmentLinksAsync();
            var lookup = BuildEnrollmentLookup(links);

            return companies.Select(c => MapToOutputDTO(c, lookup));
        }

        // Groups raw enrollment links by CompanyId for O(1) lookup while mapping.
        private static Dictionary<int, List<CompanyEnrollmentLinkDTO>> BuildEnrollmentLookup(
            List<CompanyEnrollmentLinkDTO> links)
        {
            return links
                .GroupBy(l => l.CompanyId)
                .ToDictionary(g => g.Key, g => g.ToList());
        }

        // Add a new Company
        public async Task<(NFD_CompanyOutputDTO? result, string? error)> AddCompanyAsync(
        NFD_CompanyInputDTO dto)
        {
            // التحقق من وجود المستخدم فقط إذا تم إرساله ولم يكن فارغاً
            if (dto.UserId.HasValue)
            {
                var userExists = await _repository.UserExistsAsync(dto.UserId.Value);
                if (!userExists)
                    return (null, $"User with ID {dto.UserId} not found");
            }

            var company = new NFD_Company
            {
                CompanyName = dto.CompanyName,
                CommercialRegister = dto.CommercialRegister,
                WorkField = dto.WorkField,
                Address = dto.Address,
                Phone = dto.Phone,
                Email = dto.Email,
                Logo = dto.Logo,
                Capacity = dto.Capacity,
                Status = dto.Status,
                ApprovalDate = dto.ApprovalDate,
                UserId = dto.UserId // سيتم تخزينه كقيمة صحيحة أو null
            };

            await _repository.AddCompanyAsync(company);

            return (MapToOutputDTO(company), null);
        }

        // Update an existing Company
        public async Task<NFD_CompanyOutputDTO?> UpdateCompanyAsync(
        int companyId,
         NFD_CompanyInputDTO dto)
        {
            var company = await _repository.GetCompanyByIdAsync(companyId);

            if (company == null)
                return null;

            // التحقق من وجود المستخدم في التحديث أيضاً إذا تم إرساله
            if (dto.UserId.HasValue)
            {
                var userExists = await _repository.UserExistsAsync(dto.UserId.Value);
                if (!userExists)
                    return null; // أو التعامل مع الخطأ حسب رغبتك
            }

            company.CompanyName = dto.CompanyName;
            company.CommercialRegister = dto.CommercialRegister;
            company.WorkField = dto.WorkField;
            company.Address = dto.Address;
            company.Phone = dto.Phone;
            company.Email = dto.Email;
            company.Logo = dto.Logo;
            company.Capacity = dto.Capacity;
            company.Status = dto.Status;
            company.ApprovalDate = dto.ApprovalDate;
            company.UserId = dto.UserId;

            await _repository.UpdateCompanyAsync(company);

            return MapToOutputDTO(company);
        }

        // Approve a Company
        public async Task<NFD_CompanyOutputDTO?> ApproveCompanyAsync(
        int companyId)
        {
            var company = await _repository.GetCompanyByIdAsync(companyId);

            if (company == null)
                return null;

            company.Status = NFD_CompanyStatus.Approved;
            company.ApprovalDate = DateTime.UtcNow;

            await _repository.UpdateCompanyAsync(company);

            return MapToOutputDTO(company);
        }

        // Suspend or reactivate a Company
        public async Task<NFD_CompanyOutputDTO?> SuspendCompanyAsync(
        int companyId)
        {
            var company = await _repository.GetCompanyByIdAsync(companyId);

            if (company == null)
                return null;

            if (company.Status == NFD_CompanyStatus.Suspended)
            {
                company.Status = NFD_CompanyStatus.Approved;
            }
            else
            {
                company.Status = NFD_CompanyStatus.Suspended;
            }

            await _repository.UpdateCompanyAsync(company);

            return MapToOutputDTO(company);
        }

        // Get Company Capacity
        public async Task<object?> GetCompanyCapacityAsync(
         int companyId)
        {
            var company = await _repository.GetCompanyByIdAsync(companyId);

            if (company == null)
                return null;

            // Use enrollments count as the authoritative 'used' value because
            // trainees may not have CompanyId set even when enrollments exist.
            var used = await _repository.GetEnrollmentCountAsync(companyId);
            var total = Convert.ToDecimal(company.Capacity);
            var remaining = total - used;

            return new
            {
                total,
                used,
                remaining
            };
        }

        // Delete Company
        public async Task<bool> DeleteCompanyAsync(int companyId)
        {
            var company = await _repository.GetCompanyByIdAsync(companyId);

            if (company == null)
                return false;

            company.Status = NFD_CompanyStatus.Suspended;
            await _repository.UpdateCompanyAsync(company);

            return true;
        }

        // Mapping Company Model to Output DTO.
        // enrollmentLookup (CompanyId -> its enrollment links) is optional: when
        // omitted (e.g. right after Add/Update, before any trainee is enrolled)
        // counts simply fall back to 0 instead of throwing.
        private static NFD_CompanyOutputDTO MapToOutputDTO(
            NFD_Company company,
            Dictionary<int, List<CompanyEnrollmentLinkDTO>>? enrollmentLookup = null)
        {
            // Enrollments belonging to THIS company only — this is the authoritative
            // source of truth (a Program/Batch is typically shared across many
            // companies, so counting Program.Batches directly would badly overcount).
            var myEnrollments = (enrollmentLookup != null && enrollmentLookup.TryGetValue(company.CompanyId, out var list))
                ? list
                : new List<CompanyEnrollmentLinkDTO>();

            var myBatchIds = myEnrollments.Select(e => e.BatchId).Distinct().ToHashSet();
            var myTraineeIds = myEnrollments.Select(e => e.TraineeId).Distinct().ToHashSet();

            return new NFD_CompanyOutputDTO
            {
                CompanyId = company.CompanyId,
                CompanyName = company.CompanyName,
                CommercialRegister = company.CommercialRegister,
                WorkField = company.WorkField,
                Address = company.Address,
                Phone = company.Phone,
                Email = company.Email,
                Logo = company.Logo,
                Capacity = company.Capacity,
                Status = company.Status,
                ApprovalDate = company.ApprovalDate,
                UserId = company.UserId,

                // الأعداد الحقيقية — مبنية على تسجيلات (Enrollments) هذه الشركة فعلياً،
                // وليست مساوية لعدد البرامج ولا صفراً ثابتاً   
                ProgramsCount = company.CompanyPrograms?.Count ?? 0,
                BatchesCount = myBatchIds.Count,
                TraineesCount = myTraineeIds.Count,

                Branches = company.CompanyBranches?.Select(b => new NFD_CompanyBranchOutputDTO
                {
                    BranchId = b.BranchId,
                    Location = b.Location,
                    ContactPoint = b.ContactPoint,
                    CompanyId = b.CompanyId
                }).ToList() ?? new(),

                Supervisors = company.CompanySupervisors?.Select(s => new CompanySupervisorDto
                {
                    SupervisorId = s.SupervisorId,
                    FullName = s.User?.FullName,
                    Phone = s.User?.Phone,
                    Email = s.User?.Email,
                    Status = s.Status.ToString(),
                    Department = s.Department,
                    Position = s.Position,
                    UserId = s.UserId,
                    CompanyId = s.CompanyId
                }).ToList() ?? new(),

                Programs = company.CompanyPrograms?.Select(p =>
                {
                    // Only the batches of this program where OUR company actually
                    // has enrolled trainees — a program/batch can be shared with
                    // other companies, so we must not show their trainees here.
                    var ourBatchesInProgram = (p.Program?.Batches ?? new List<NFD_Batch>())
                        .Where(b => myBatchIds.Contains(b.BatchId))
                        .Select(b => new NFD_CompanyProgramBatchDTO
                        {
                            BatchId = b.BatchId,
                            BatchName = b.BatchName,
                            StartDate = b.StartDate,
                            EndDate = b.EndDate,
                            TraineesCount = myEnrollments.Count(e => e.BatchId == b.BatchId)
                        }).ToList();

                    return new NFD_CompanyProgramOutputDTO
                    {
                        CompanyId = p.CompanyId,
                        ProgramId = p.ProgramId,
                        Title = p.Program?.Title,
                        Track = p.Program?.Track?.Name,
                        BatchesCount = ourBatchesInProgram.Count,
                        TraineesCount = ourBatchesInProgram.Sum(b => b.TraineesCount),
                        Batches = ourBatchesInProgram
                    };
                }).ToList() ?? new(),

                Payments = company.CompanyPayments?.Select(p => new CompanyPaymentResponseDto
                {
                    CompanyPaymentId = p.CompanyPaymentId,
                    TotalAmount = p.TotalAmount,
                    Status = p.Status,
                    CompanyId = p.CompanyId,
                    CompanyName = company.CompanyName,
                    BatchId = p.BatchId
                }).ToList() ?? new(),

                Departments = company.Departments?.Select(d => new DepartmentDto
                {
                    DepartmentId = d.DepartmentId,
                    Name = d.Name,
                    CompanyId = d.CompanyId
                }).ToList() ?? new()
            };
        }
    }
}