// <auto-generated>
// Added as part of Nafadh backend upgrade (Phase 2 - Contract Alignment).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.DTOs;
using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;
using Nafadh_Backend.Repositories;

namespace Nafadh_Backend.Services
{
    public class ConversationService : IConversationService
    {
        private readonly IConversationRepository _repository;

        public ConversationService(IConversationRepository repository)
        {
            _repository = repository;
        }

        public async Task<List<ConversationListItemDTO>> GetAsync(NFD_ConversationType? type, int? participantUserId, NFD_SupportTicketStatus? status)
        {
            var conversations = await _repository.GetAsync(type, participantUserId, status);
            return conversations.Select(MapToListItem).ToList();
        }

        public async Task<ConversationDetailDTO?> GetByIdAsync(int conversationId)
        {
            var conversation = await _repository.GetByIdAsync(conversationId);
            if (conversation == null) return null;
            return MapToDetail(conversation);
        }

        public async Task<ConversationDetailDTO> CreateAsync(CreateConversationDTO dto)
        {
            var conversation = new NFD_SupportTicket
            {
                Type = dto.Type,
                Category = dto.Category,
                Subject = dto.Subject,
                // Message column retains the opening message text for backward
                // compatibility with the original ticket-only read paths; the
                // canonical thread content lives in NFD_Messages from here on.
                Message = dto.FirstMessage,
                Status = Enums.NFD_SupportTicketStatus.Open,
                CreatedAt = DateTime.UtcNow,
                UserId = dto.StartedByUserId
            };

            var firstMessage = new NFD_Message
            {
                Content = dto.FirstMessage,
                SentDate = DateTime.UtcNow,
                Status = Enums.NFD_MessageStatus.Sent,
                SenderId = dto.StartedByUserId
            };

            var created = await _repository.CreateAsync(conversation, firstMessage);
            var full = await _repository.GetByIdAsync(created.TicketId);
            return MapToDetail(full!);
        }

        public async Task<ConversationMessageDTO> AddMessageAsync(int conversationId, AddConversationMessageDTO dto)
        {
            var message = new NFD_Message
            {
                Content = dto.Content,
                SentDate = DateTime.UtcNow,
                Status = Enums.NFD_MessageStatus.Sent,
                SenderId = dto.SenderId,
                TicketId = conversationId
            };

            var created = await _repository.AddMessageAsync(message);

            return new ConversationMessageDTO
            {
                MessageId = created.MessageId,
                Content = created.Content,
                SentDate = created.SentDate,
                Status = created.Status,
                SenderId = created.SenderId,
                TicketId = created.TicketId
            };
        }

        public Task UpdateStatusAsync(int conversationId, UpdateConversationStatusDTO dto)
        {
            return _repository.UpdateStatusAsync(conversationId, dto.Status);
        }

        private static ConversationListItemDTO MapToListItem(NFD_SupportTicket t)
        {
            var lastMessage = t.Messages?.OrderByDescending(m => m.SentDate).FirstOrDefault();

            return new ConversationListItemDTO
            {
                ConversationId = t.TicketId,
                Type = t.Type,
                Category = t.Category,
                Subject = t.Subject,
                Status = t.Status,
                LastMessagePreview = lastMessage?.Content ?? t.Message,
                LastMessageDate = lastMessage?.SentDate ?? t.CreatedAt,
                UnreadCount = t.Messages?.Count(m => m.Status != Enums.NFD_MessageStatus.Read) ?? 0,
                StartedByName = t.User?.FullName
            };
        }

        private static ConversationDetailDTO MapToDetail(NFD_SupportTicket t)
        {
            var listItem = MapToListItem(t);

            return new ConversationDetailDTO
            {
                ConversationId = listItem.ConversationId,
                Type = listItem.Type,
                Category = listItem.Category,
                Subject = listItem.Subject,
                Status = listItem.Status,
                LastMessagePreview = listItem.LastMessagePreview,
                LastMessageDate = listItem.LastMessageDate,
                UnreadCount = listItem.UnreadCount,
                StartedByName = listItem.StartedByName,
                Messages = t.Messages?
                    .OrderBy(m => m.SentDate)
                    .Select(m => new ConversationMessageDTO
                    {
                        MessageId = m.MessageId,
                        Content = m.Content,
                        SentDate = m.SentDate,
                        Status = m.Status,
                        SenderId = m.SenderId,
                        SenderName = m.Sender?.FullName,
                        ReceiverId = m.ReceiverId,
                        TicketId = m.TicketId
                    }).ToList() ?? new List<ConversationMessageDTO>()
            };
        }
    }
}
