// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.DTOs;
using Nafadh_Backend.Models;
using Nafadh_Backend.Repositories;

namespace Nafadh_Backend.Services
{
    public class EvaluationCriterionService : IEvaluationCriterionService
    {
        private readonly IEvaluationCriterionRepository _repository;
        private readonly IEvaluationTemplateRepository _templateRepository;

        public EvaluationCriterionService(IEvaluationCriterionRepository repository, IEvaluationTemplateRepository templateRepository)
        {
            _repository = repository;
            _templateRepository = templateRepository;
        }

        // ==========================================
        // Get Criteria By Template Id
        public async Task<List<EvaluationCriterionOutputDTO>> GetCriteriaByTemplateIdAsync(int templateId)
        {
            var criteria = await _repository.GetCriteriaByTemplateIdAsync(templateId);

            var result = new List<EvaluationCriterionOutputDTO>();

            foreach (var item in criteria)
            {
                result.Add(new EvaluationCriterionOutputDTO
                {
                    CriteriaId = item.CriteriaId,
                    TemplateId = item.TemplateId,
                    Name = item.Name,
                    Weight = item.Weight,
                    MaxPoints = item.MaxPoints
                });
            }

            return result;
        }

        // ==========================================
        // Get Criterion Details
        public async Task<EvaluationCriterionDetailsDTO?> GetCriterionByIdAsync(int criteriaId)
        {
            var criterion = await _repository.GetCriterionByIdAsync(criteriaId);

            if (criterion == null)
                return null;

            return new EvaluationCriterionDetailsDTO
            {
                CriteriaId = criterion.CriteriaId,
                TemplateId = criterion.TemplateId,
                Name = criterion.Name,
                Weight = criterion.Weight,
                MaxPoints = criterion.MaxPoints
            };
        }

        // ==========================================
        // Create Criterion
        public async Task CreateCriterionAsync(EvaluationCriterionInputDTO input)
        {
            // Check if the template exists
            var template = await _templateRepository.GetTemplateByIdAsync(input.TemplateId);

            if (template == null)
                throw new Exception("Evaluation Template not found.");

            var criterion = new NFD_EvaluationCriterion
            {
                TemplateId = input.TemplateId,
                Name = input.Name,
                Weight = input.Weight,
                MaxPoints = input.MaxPoints
            };

            await _repository.AddCriterionAsync(criterion);
        }

        // ==========================================
        // Update Criterion
        public async Task<bool> UpdateCriterionAsync(int criteriaId, EvaluationCriterionInputDTO input)
        {
            var criterion = await _repository.GetCriterionByIdAsync(criteriaId);

            if (criterion == null)
                return false;

            // Check if the template exists
            var template = await _templateRepository.GetTemplateByIdAsync(input.TemplateId);

            if (template == null)
                throw new Exception("Evaluation Template not found.");

            criterion.TemplateId = input.TemplateId;
            criterion.Name = input.Name;
            criterion.Weight = input.Weight;
            criterion.MaxPoints = input.MaxPoints;

            await _repository.UpdateCriterionAsync(criterion);

            return true;
        }

        // ==========================================
        // Delete Criterion
        public async Task<bool> DeleteCriterionAsync(int criteriaId)
        {
            var criterion = await _repository.GetCriterionByIdAsync(criteriaId);

            if (criterion == null)
                return false;

            await _repository.DeleteCriterionAsync(criterion);

            return true;
        }

        // ==========================================
        // Check Total Weight
        public async Task<bool> CheckTemplateWeightsAsync(int templateId)
        {
            var criteria = await _repository.GetCriteriaByTemplateIdAsync(templateId);

            decimal totalWeight = criteria.Sum(c => c.Weight);

            return totalWeight == 100;
        }
    }
}