
// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Nafadh_Backend.DTOs;

namespace Nafadh_Backend.Services
{
    public interface IBatchService
    {
        Task<List<BatchDto>> GetAllAsync(int? programId, string? status, DateTime? from, DateTime? to);
        Task<BatchDto?> GetByIdAsync(int id);
        Task<BatchDto> CreateAsync(CreateBatchDto dto);
        Task<bool> UpdateAsync(int id, UpdateBatchDto dto);
        Task<bool> DeleteAsync(int id);
        Task<List<BatchTraineeDto>> GetTraineesAsync(int batchId);
        Task<BatchCapacityDto?> GetCapacityAsync(int batchId);
    }
}
