//// <auto-generated>
//// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
//// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
//// </auto-generated>

using Nafadh_Backend.Models;
using static Nafadh_Backend.DTOs.CertificateDTO;

namespace Nafadh_Backend.Services
{
    public interface ICertificateService
    {
        // TODO: define business-logic contract methods for this entity


        Task<CertificateOutputDTO?> GetCertificateByEnrollmentIdAsync(int enrollmentId);
        Task<CertificateOutputDTO> AddCertificateAsync(CertificateInputDTO dto);
        Task<byte[]?> DownloadCertificateAsync(int id);
        Task<List<CertificateOutputDTO>> GetCertificatesByTraineeIdAsync(int traineeId);
    }
}
