//// <auto-generated>
//// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
//// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
//// </auto-generated>

//using Nafadh_Backend.DTOs;

//namespace Nafadh_Backend.Services
//{
//    public interface ICertificateService
//    {
//        // Get certificate by ID
//        Task<NFD_CertificateOutputDTO?> GetCertificateByIdAsync(
//            int certificateId);

//        // Add a new certificate
//        Task<NFD_CertificateOutputDTO> AddCertificateAsync(
//            NFD_CertificateInputDTO dto);

//        // Update an existing certificate
//        Task<NFD_CertificateOutputDTO?> UpdateCertificateAsync(
//            int certificateId,
//            NFD_CertificateInputDTO dto);

//        // Delete certificate
//        Task<bool> DeleteCertificateAsync(
//            int certificateId);
//    }
//}