// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>


using Nafadh_Backend.Models;
using Nafadh_Backend.DTOs.CompanyPayment;
namespace Nafadh_Backend.Services
{
    public interface ICompanyPaymentScheduleService
    {
        Task<IEnumerable<CompanyPaymentScheduleResponseDto>>
            GetPaymentScheduleAsync(
                int companyPaymentId);


        Task GenerateScheduleAsync(
            CreateCompanyPaymentScheduleDto dto);


        Task<bool> MarkPaidAsync(
            int id,
            MarkCompanyPaymentSchedulePaidDto dto);


        Task<IEnumerable<CompanyPaymentScheduleResponseDto>>
            GetOverdueAsync();
    }
}