// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.DTOs;
using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;

namespace Nafadh_Backend.Services
{
    public interface IEvaluationTemplateService
    {
        // List templates (optionally filter by type)
        Task<List<EvaluationTemplateOutputDTO>> GetTemplatesAsync(NFD_EvaluationType? type);

        // Get template details with criteria
        Task<EvaluationTemplateDetailsDTO?> GetTemplateByIdAsync(int templateId);

        // Create template
        Task CreateTemplateAsync(EvaluationTemplateInputDTO input);

        // Update template
        Task<bool> UpdateTemplateAsync(int templateId, EvaluationTemplateInputDTO input);

        // Delete template
        Task<bool> DeleteTemplateAsync(int templateId);
    }
}