// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.DTOs;

namespace Nafadh_Backend.Services
{
    public interface IEvaluationService
    {
        Task<IEnumerable<EvaluationDTO>> GetEvaluationsByEnrollmentIdAsync(int enrollmentId);
        Task<IEnumerable<EvaluationDTO>> GetEvaluationsByTrainerIdAsync(int trainerId);
        Task<EvaluationDTO?> GetEvaluationByIdAsync(int evaluationId);
        Task<EvaluationDTO> CreateEvaluationAsync(CreateEvaluationDTO createDto);
        Task UpdateEvaluationAsync(int id, UpdateEvaluationDTO updateDto);
        Task<double> GetAverageScoreByEnrollmentIdAsync(int enrollmentId);

        // NEW: fixed-bucket rollup for Admin Reports — groups this enrollment's
        // evaluations by their template's Type and averages each bucket.
        Task<EvaluationBucketRollupDTO> GetBucketRollupByEnrollmentIdAsync(int enrollmentId);
    }
}
