// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.Models;
using static Nafadh_Backend.DTOs.ExcuseDto;

namespace Nafadh_Backend.Services
{
    public interface IExcuseService
    {
        Task<ExcuseReadDto?> GetByDailyAttendanceIdAsync(int dailyAttendanceId);
        Task<ExcuseReadDto> CreateAsync(CreateExcuseDto dto);
        Task<bool> ReviewAsync(int id, ReviewExcuseDto dto);
        Task<List<ExcuseReadDto>> GetPendingAsync();
    }
}