// <auto-generated>
// Added as part of Nafadh backend upgrade (Phase 2 - Contract Alignment).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.DTOs;
using Nafadh_Backend.Enums;

namespace Nafadh_Backend.Services
{
    public interface IFeedbackService
    {
        Task<List<FeedbackCriterionDTO>> GetCriteriaAsync(NFD_FeedbackType? appliesTo);
        Task<FeedbackDTO> CreateFeedbackAsync(CreateFeedbackDTO dto);
        Task<FeedbackSummaryDTO> GetTrainerSummaryAsync(int trainerId);
        Task<FeedbackSummaryDTO> GetBatchSummaryAsync(int batchId);
        Task<FeedbackPendingDTO> GetPendingAsync(int moduleId, int traineeId);
    }
}
