// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Microsoft.AspNetCore.Http.HttpResults;
using Nafadh_Backend.DTOs;
using Nafadh_Backend.Models;

namespace Nafadh_Backend.Services
{
    public interface INotificationService
    {
        // TODO: define business-logic contract methods for this entity

        //Get User Notifications
        Task<List<NotificationDTO>> GetByUserIdAsync(int userId);
        //Create Notification
        Task CreateAsync(CreateNotificationDTO dto);

        //Mark Notification As Read
        Task MarkAsReadAsync(int id);

        //Mark All Notifications As Read
        Task MarkAllAsReadAsync(int userId);
    }
}