// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;
using static Nafadh_Backend.DTOs.ProjectDTOs;

namespace Nafadh_Backend.Services
{
    public interface IProjectService
    {
        
        Task<IEnumerable<ProjectDto>> GetAllAsync(int? programId, NFD_ProjectStatus? status);

        Task<ProjectDto?> GetByIdAsync(int id);

        Task<ProjectDto> CreateAsync(CreateProjectDto dto);

        Task<bool> UpdateAsync(int id, UpdateProjectDto dto);

        Task<bool> DeleteAsync(int id);

        Task<IEnumerable<ProjectDto>> GetByProgramIdAsync(int programId);


    }
}