// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.DTOs;
using Nafadh_Backend.Models;
using static Nafadh_Backend.DTOs.ProgramDTO;

namespace Nafadh_Backend.Services
{
    public interface IProgramService
    {
        Task<IEnumerable<ProgramDTO>> GetAllProgramsAsync(ProgramFilterDto filter);
        Task<ProgramDTO?> GetProgramByIdAsync(int id);
        Task<(ProgramDTO? result, string? error)> CreateProgramAsync(CreateProgramDto dto);
        Task<(ProgramDTO? result, string? error)> UpdateProgramAsync(int id, UpdateProgramDto dto);
        Task<bool> DeleteProgramAsync(int id);

        Task<IEnumerable<BatchSummaryDto>?> GetBatchesByProgramIdAsync(int programId);
        Task<IEnumerable<ModuleSummaryDto>?> GetModulesByProgramIdAsync(int programId);
        Task<IEnumerable<EligibleCompanyDto>?> GetEligibleCompaniesByProgramIdAsync(int programId);
    }
}