// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;
using Nafadh_Backend.DTOs;

namespace Nafadh_Backend.Services
{
    public interface IReportService
    {
        // TODO: define business-logic contract methods for this entity
        Task<List<ReportOutputDTO>> GetReportsAsync(NFD_ReportType? type, int? userId);
        Task<ReportOutputDTO> GenerateReportAsync(ReportInputDTO dto);
        Task<ReportOutputDTO?> GetReportByIdAsync(int reportId);
        Task<string?> DownloadReportAsync(int reportId);
    }
}