// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.Models;
using static Nafadh_Backend.DTOs.TraineePaymentSchedule;

namespace Nafadh_Backend.Services
{
    public interface ITraineePaymentScheduleService
    {

        Task<IEnumerable<NFD_TraineePaymentSchedule>>
            GetPaymentScheduleAsync(
                int traineePaymentId);



        Task<IEnumerable<NFD_TraineePaymentSchedule>>
            GenerateInstallmentsAsync(
                int traineePaymentId,
                decimal totalAmount,
                int months);



        Task<bool>
            MarkAsPaidAsync(int id);



        Task<IEnumerable<NFD_TraineePaymentSchedule>>
            GetOverdueAsync();
    }
}