// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>
using Microsoft.AspNetCore.Http;

using Nafadh_Backend.DTOs;

namespace Nafadh_Backend.Services
{
    public interface ITrainerService
    {
        Task<(List<TrainerListItemDto> Items, int TotalCount)> GetAllAsync(TrainerFilterDto filter);

        Task<TrainerProfileDto?> GetByIdAsync(int id);
        // Retrieves the trainer profile associated with a specific user account
        Task<TrainerProfileDto?> GetByUserIdAsync(int userId);

        Task<TrainerProfileDto?> CreateAsync(TrainerCreateDto dto);

        Task<bool> UpdateAsync(int id, TrainerUpdateDto dto);
        // =====================================================
        // TRAINER PROFILE IMAGE
        // =====================================================

        // Uploads a new trainer profile image
        // and returns its public URL after saving.
        Task<string?> UploadProfileImageAsync(
            int trainerId,
            IFormFile file
        );

        Task<bool> UpdateStatusAsync(int id, TrainerStatusUpdateDto dto);

        Task<List<TrainerBatchDto>> GetBatchesAsync(int id);

        Task<List<TrainerEvaluationDto>> GetEvaluationsAsync(int id);
    }
}
