// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;
using Nafadh_Backend.Repositories;

namespace Nafadh_Backend.Services
{
    public class MessageService : IMessageService
    {
        private readonly IMessageRepository _repository;

        public MessageService(IMessageRepository repository)
        {
            _repository = repository;
        }

        // 1. GET: /api/Message/conversation/{userId1}/{userId2}:
        public async Task<List<NFD_Message>> GetConversationAsync(int userId1, int userId2)
        {
            return await _repository.GetConversationAsync(userId1, userId2);
        }


        // 2. GET: /api/Message/inbox/{userId}:
        public async Task<List<NFD_Message>> GetUserInboxAsync(int userId)
        {
            return await _repository.GetUserInboxAsync(userId);
        }


        // 3. POST: /api/Message:
        public async Task AddAsync(NFD_Message message)
        {
            if (message.Status == 0)
            {
                message.Status = NFD_MessageStatus.Sent;
            }

            await _repository.AddAsync(message);
        }


        // 4. PUT: /api/Message/{id}/status:
        public async Task<bool> UpdateStatusAsync(int messageId, NFD_MessageStatus status)
        {
            var message = await _repository.GetByIdAsync(messageId);
            if (message == null)
            {
                return false;
            }

            await _repository.UpdateStatusAsync(messageId, status);
            return true;
        }

        // 5. GET: /api/Message/user/{userId}/unread-count:
        public async Task<int> GetUnreadCountAsync(int userId)
        {
            return await _repository.GetUnreadCountAsync(userId);
        }

    }
}