// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.DTOs;
using Nafadh_Backend.Models;
using Nafadh_Backend.Repositories;

namespace Nafadh_Backend.Services
{
    public class ProgramService : IProgramService
    {
        private readonly IProgramRepository _repository;

        public ProgramService(IProgramRepository repository)
        {
            _repository = repository;
        }

        public async Task<IEnumerable<ProgramDto>> GetAllProgramsAsync(ProgramFilterDto filter)
        {
            var programs = await _repository.GetAllAsync(filter.TrackId, filter.Status, filter.Category);
            return programs.Select(MapToDto);
        }

    }
}