// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;
using Nafadh_Backend.Repositories;
using Nafadh_Backend.DTOs;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Nafadh_Backend.Services
{
    public class ReportService : IReportService
    {
        private readonly IReportRepository _repository;
        private readonly IConfiguration _configuration;


        public ReportService(
            IReportRepository repository,
            IConfiguration configuration
        )
        {
            _repository = repository;
            _configuration = configuration;
        }

        // ==========================================================
        // GET Reports
        // ==========================================================

        public async Task<List<ReportOutputDTO>> GetReportsAsync(
            NFD_ReportType? type,
            int? userId)
        {
            var reports = await _repository.GetReportsAsync(type, userId);

            return reports.Select(r => new ReportOutputDTO
            {
                ReportId = r.ReportId,
                Type = r.Type,
                FiltersJson = r.FiltersJson,
                GeneratedAt = r.GeneratedAt,
                FileUrl = r.FileUrl,
                GeneratedByUserId = r.GeneratedByUserId
            }).ToList();
        }


        // ==========================================================
        // Generate Trainer Portal PDF Report
        // This report is isolated from the shared report generator
        // so other portals are not affected by Trainer Portal design.
        // ==========================================================

        public async Task<ReportOutputDTO> GenerateTrainerPortalReportAsync(
            ReportInputDTO dto
        )
        {// ======================================================
         // External Trainer Portal Reports Storage
         // ======================================================

            // Store Trainer Portal reports outside the project
            // so generated PDF files are never included in Git.

            var reportsFolder =
                _configuration[
                    "Storage:TrainerReportsPath"
                ];


            if (
                string.IsNullOrWhiteSpace(
                    reportsFolder
                )
            )
            {
                throw new InvalidOperationException(
                    "Trainer reports storage path is not configured."
                );
            }


            Directory.CreateDirectory(
                reportsFolder
            );


            var generatedAt =
                DateTime.Now;


            var fileName =
                $"trainer-portal-report-{dto.TrainerId ?? 0}-{generatedAt:yyyyMMddHHmmssfff}.pdf";


            var fullPath =
                Path.Combine(
                    reportsFolder,
                    fileName
                );


            // ======================================================
            // Trainer KPIs
            // ======================================================

            TrainerKpisDTO? kpis =
                null;


            if (dto.TrainerId.HasValue)
            {
                kpis =
                    await _repository.GetTrainerKpisAsync(
                        dto.TrainerId.Value
                    );
            }


            // ======================================================
            // Arabic report type
            // ======================================================

            var reportTypeName =
                dto.Type switch
                {
                    NFD_ReportType.Attendance =>
                        "تقرير الحضور والغياب",

                    NFD_ReportType.Performance =>
                        "تقرير الأداء والمهام",

                    NFD_ReportType.Financial =>
                        "التقرير المالي",

                    NFD_ReportType.Enrollment =>
                        "تقرير التسجيل",

                    NFD_ReportType.Custom =>
                        "التقرير الشامل",

                    _ =>
                        "تقرير المدرب"
                };


            // ======================================================
            // Generate Trainer Portal PDF
            // ======================================================

            var document =
                Document.Create(container =>
                {
                    container.Page(page =>
                    {
                        page.Size(
                            PageSizes.A4
                        );


                        page.Margin(35);


                        page.DefaultTextStyle(
                            style =>
                                style.FontSize(11)
                        );


                        // ===========================================
                        // HEADER
                        // ===========================================

                        page.Header()
                            .Background("#003B82")
                            .Padding(20)
                            .Column(header =>
                            {
                                header.Item()
                                    .AlignCenter()
                                    .Text("تقرير المدرب")
                                    .FontSize(24)
                                    .Bold()
                                    .FontColor(
                                        Colors.White
                                    );


                                header.Item()
                                    .PaddingTop(5)
                                    .AlignCenter()
                                    .Text(
                                        "بوابة نفاذ للتدريب والتطوير"
                                    )
                                    .FontSize(10)
                                    .FontColor(
                                        Colors.White
                                    );
                            });


                        // ===========================================
                        // CONTENT
                        // ===========================================

                        page.Content()
                            .PaddingVertical(24)
                            .Column(column =>
                            {
                                column.Spacing(18);


                                // ===================================
                                // REPORT INFORMATION
                                // ===================================

                                column.Item()
                                    .Border(1)
                                    .BorderColor(
                                        Colors.Grey.Lighten2
                                    )
                                    .Padding(16)
                                    .Column(info =>
                                    {
                                        info.Spacing(9);


                                        info.Item()
                                            .AlignRight()
                                            .Text(
                                                reportTypeName
                                            )
                                            .FontSize(18)
                                            .Bold()
                                            .FontColor(
                                                "#003B82"
                                            );


                                        info.Item()
                                            .LineHorizontal(1)
                                            .LineColor(
                                                Colors.Grey.Lighten2
                                            );


                                        if (
                                            dto.TrainerId.HasValue
                                        )
                                        {
                                            info.Item()
                                                .AlignRight()
                                                .Text(text =>
                                                {
                                                    text.Span(
                                                        "رقم المدرب: "
                                                    )
                                                    .SemiBold();

                                                    text.Span(
                                                        dto.TrainerId
                                                            .Value
                                                            .ToString()
                                                    );
                                                });
                                        }


                                        info.Item()
                                            .AlignRight()
                                            .Text(text =>
                                            {
                                                text.Span(
                                                    "تاريخ التقرير: "
                                                )
                                                .SemiBold();

                                                text.Span(
                                                    generatedAt.ToString(
                                                        "yyyy-MM-dd"
                                                    )
                                                );
                                            });


                                        info.Item()
                                            .AlignRight()
                                            .Text(text =>
                                            {
                                                text.Span(
                                                    "وقت الإنشاء: "
                                                )
                                                .SemiBold();

                                                text.Span(
                                                    generatedAt.ToString(
                                                        "HH:mm"
                                                    )
                                                );
                                            });
                                    });


                                // ===================================
                                // KPI SUMMARY
                                // ===================================

                                if (kpis != null)
                                {
                                    column.Item()
                                        .AlignRight()
                                        .Text(
                                            "ملخص الأداء"
                                        )
                                        .FontSize(18)
                                        .Bold()
                                        .FontColor(
                                            "#0F172A"
                                        );


                                    column.Item()
                                        .Row(row =>
                                        {
                                            row.Spacing(10);


                                            // Attendance card
                                            row.RelativeItem()
                                                .Background(
                                                    "#F0F9FF"
                                                )
                                                .Border(1)
                                                .BorderColor(
                                                    "#BAE6FD"
                                                )
                                                .Padding(14)
                                                .Column(card =>
                                                {
                                                    card.Item()
                                                        .AlignCenter()
                                                        .Text(
                                                            "الحضور"
                                                        )
                                                        .FontSize(10)
                                                        .FontColor(
                                                            "#64748B"
                                                        );


                                                    card.Item()
                                                        .PaddingTop(6)
                                                        .AlignCenter()
                                                        .Text(
                                                            $"{kpis.AttendanceRate:0.#}%"
                                                        )
                                                        .FontSize(21)
                                                        .Bold()
                                                        .FontColor(
                                                            "#003B82"
                                                        );
                                                });


                                            // Tasks card
                                            row.RelativeItem()
                                                .Background(
                                                    "#F0F9FF"
                                                )
                                                .Border(1)
                                                .BorderColor(
                                                    "#BAE6FD"
                                                )
                                                .Padding(14)
                                                .Column(card =>
                                                {
                                                    card.Item()
                                                        .AlignCenter()
                                                        .Text(
                                                            "إنجاز المهام"
                                                        )
                                                        .FontSize(10)
                                                        .FontColor(
                                                            "#64748B"
                                                        );


                                                    card.Item()
                                                        .PaddingTop(6)
                                                        .AlignCenter()
                                                        .Text(
                                                            $"{kpis.TaskCompletionRate:0.#}%"
                                                        )
                                                        .FontSize(21)
                                                        .Bold()
                                                        .FontColor(
                                                            "#003B82"
                                                        );
                                                });


                                            // Grade card
                                            row.RelativeItem()
                                                .Background(
                                                    "#F0F9FF"
                                                )
                                                .Border(1)
                                                .BorderColor(
                                                    "#BAE6FD"
                                                )
                                                .Padding(14)
                                                .Column(card =>
                                                {
                                                    card.Item()
                                                        .AlignCenter()
                                                        .Text(
                                                            "التقييم الفني"
                                                        )
                                                        .FontSize(10)
                                                        .FontColor(
                                                            "#64748B"
                                                        );


                                                    card.Item()
                                                        .PaddingTop(6)
                                                        .AlignCenter()
                                                        .Text(
                                                            $"{kpis.AvgTechnicalGrade:0.#}"
                                                        )
                                                        .FontSize(21)
                                                        .Bold()
                                                        .FontColor(
                                                            "#003B82"
                                                        );


                                                    card.Item()
                                                        .AlignCenter()
                                                        .Text(
                                                            "من 100"
                                                        )
                                                        .FontSize(8)
                                                        .FontColor(
                                                            "#94A3B8"
                                                        );
                                                });
                                        });


                                    // ===================================
                                    // KPI DETAILS
                                    // ===================================

                                    column.Item()
                                        .Border(1)
                                        .BorderColor(
                                            Colors.Grey.Lighten2
                                        )
                                        .Padding(16)
                                        .Column(details =>
                                        {
                                            details.Spacing(10);


                                            details.Item()
                                                .AlignRight()
                                                .Text(
                                                    "تفاصيل مؤشرات الأداء"
                                                )
                                                .FontSize(15)
                                                .Bold();


                                            details.Item()
                                                .LineHorizontal(1)
                                                .LineColor(
                                                    Colors.Grey.Lighten2
                                                );


                                            details.Item()
                                                .AlignRight()
                                                .Text(
                                                    $"نسبة الحضور العامة: {kpis.AttendanceRate:0.#}%"
                                                );


                                            details.Item()
                                                .AlignRight()
                                                .Text(
                                                    $"معدل إنجاز المهام: {kpis.TaskCompletionRate:0.#}%"
                                                );


                                            details.Item()
                                                .AlignRight()
                                                .Text(
                                                    $"متوسط الدرجات الفنية: {kpis.AvgTechnicalGrade:0.#} من 100"
                                                );
                                        });
                                }


                                // ===================================
                                // SYSTEM NOTE
                                // ===================================

                                column.Item()
                                    .Background(
                                        "#F8FAFC"
                                    )
                                    .Padding(12)
                                    .AlignRight()
                                    .Text(
                                        "تم إعداد هذا التقرير تلقائيًا اعتمادًا على البيانات المسجلة في بوابة نفاذ."
                                    )
                                    .FontSize(9)
                                    .FontColor(
                                        "#64748B"
                                    );


                                // FiltersJson is internal system data,
                                // so it is not displayed in the PDF.
                            });


                        // ===========================================
                        // FOOTER
                        // ===========================================

                        page.Footer()
                            .PaddingTop(10)
                            .Row(row =>
                            {
                                row.RelativeItem()
                                    .AlignLeft()
                                    .Text(
                                        generatedAt.ToString(
                                            "yyyy-MM-dd"
                                        )
                                    )
                                    .FontSize(8)
                                    .FontColor(
                                        "#94A3B8"
                                    );


                                row.RelativeItem()
                                    .AlignRight()
                                    .Text(
                                        "بوابة نفاذ للتدريب والتطوير"
                                    )
                                    .FontSize(8)
                                    .FontColor(
                                        "#94A3B8"
                                    );
                            });
                    });
                });


            // ======================================================
            // Save PDF
            // ======================================================

            document.GeneratePdf(
                fullPath
            );


            var fileUrl = fullPath;



            // ======================================================
            // Save report metadata
            // ======================================================

            var report =
                new NFD_Report
                {
                    Type =
                        dto.Type,

                    FiltersJson =
                        dto.FiltersJson,

                    GeneratedAt =
                        generatedAt,

                    FileUrl =
                        fileUrl,

                    GeneratedByUserId =
                        dto.GeneratedByUserId
                };


            await _repository.AddReportAsync(
                report
            );


            return new ReportOutputDTO
            {
                ReportId =
                    report.ReportId,

                Type =
                    report.Type,

                FiltersJson =
                    report.FiltersJson,

                GeneratedAt =
                    report.GeneratedAt,

                FileUrl =
                    report.FileUrl,

                GeneratedByUserId =
                    report.GeneratedByUserId
            };
        }
        // ==========================================================
        // Generate PDF Report
        // ==========================================================

        public async Task<ReportOutputDTO> GenerateReportAsync(ReportInputDTO dto)
        {
            // مجلد حفظ التقارير
            var reportsFolder = Path.Combine(
                Directory.GetCurrentDirectory(),
                "wwwroot",
                "reports"
            );

            // إنشاء المجلد إذا لم يكن موجوداً
            Directory.CreateDirectory(reportsFolder);

            var generatedAt = DateTime.Now;

            // اسم فريد للملف
            var fileName =
                $"trainer-report-{dto.TrainerId ?? 0}-{generatedAt:yyyyMMddHHmmssfff}.pdf";

            var fullPath = Path.Combine(reportsFolder, fileName);

            // ======================================================
            // جلب مؤشرات المدرب
            // ======================================================

            TrainerKpisDTO? kpis = null;

            if (dto.TrainerId.HasValue)
            {
                kpis = await _repository.GetTrainerKpisAsync(
                    dto.TrainerId.Value
                );
            }

            // ======================================================
            // إنشاء ملف PDF
            // ======================================================

            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);

                    page.Margin(30);

                    page.DefaultTextStyle(style =>
                        style.FontSize(12)
                    );

                    // ---------------- Header ----------------

                    page.Header()
                        .AlignCenter()
                        .Text("تقرير المدرب")
                        .FontSize(22)
                        .Bold();

                    // ---------------- Content ----------------

                    page.Content()
                        .PaddingVertical(20)
                        .Column(column =>
                        {
                            column.Spacing(12);

                            column.Item()
                                .AlignRight()
                                .Text($"نوع التقرير: {dto.Type}");

                            if (dto.TrainerId.HasValue)
                            {
                                column.Item()
                                    .AlignRight()
                                    .Text(
                                        $"رقم المدرب: {dto.TrainerId.Value}"
                                    );
                            }

                            column.Item()
                                .AlignRight()
                                .Text(
                                    $"تاريخ الإنشاء: {generatedAt:yyyy-MM-dd HH:mm}"
                                );

                            // ----------------------------------
                            // KPIs
                            // ----------------------------------

                            if (kpis != null)
                            {
                                column.Item()
                                    .PaddingTop(15)
                                    .AlignRight()
                                    .Text("مؤشرات الأداء")
                                    .FontSize(17)
                                    .Bold();

                                column.Item()
                                    .AlignRight()
                                    .Text(
                                        $"نسبة الحضور العامة: {kpis.AttendanceRate}%"
                                    );

                                column.Item()
                                    .AlignRight()
                                    .Text(
                                        $"معدل إنجاز المهام: {kpis.TaskCompletionRate}%"
                                    );

                                column.Item()
                                    .AlignRight()
                                    .Text(
                                        $"متوسط الدرجات الفنية: {kpis.AvgTechnicalGrade} / 100"
                                    );
                            }

                            // ----------------------------------
                            // Filters
                            // ----------------------------------

                            if (!string.IsNullOrWhiteSpace(dto.FiltersJson))
                            {
                                column.Item()
                                    .PaddingTop(15)
                                    .AlignRight()
                                    .Text("بيانات التقرير")
                                    .FontSize(15)
                                    .Bold();

                                column.Item()
                                    .AlignRight()
                                    .Text(dto.FiltersJson);
                            }
                        });

                    // ---------------- Footer ----------------

                    page.Footer()
                        .AlignCenter()
                        .Text(text =>
                        {
                            text.Span("بوابة نفاذ - ");
                            text.Span("تقرير المدرب");
                        });
                });
            });

            // حفظ PDF داخل wwwroot/reports
            document.GeneratePdf(fullPath);

            // نخزن المسار النسبي فقط في قاعدة البيانات
            var fileUrl = $"reports/{fileName}";

            // ======================================================
            // حفظ سجل التقرير في قاعدة البيانات
            // ======================================================

            var report = new NFD_Report
            {
                Type = dto.Type,
                FiltersJson = dto.FiltersJson,
                GeneratedAt = generatedAt,
                FileUrl = fileUrl,
                GeneratedByUserId = dto.GeneratedByUserId
            };

            await _repository.AddReportAsync(report);

            // ======================================================
            // Return
            // ======================================================

            return new ReportOutputDTO
            {
                ReportId = report.ReportId,
                Type = report.Type,
                FiltersJson = report.FiltersJson,
                GeneratedAt = report.GeneratedAt,
                FileUrl = report.FileUrl,
                GeneratedByUserId = report.GeneratedByUserId
            };
        }

        // ==========================================================
        // Generate Trainer Trainees PDF Report
        // ==========================================================

        public async Task<ReportOutputDTO> GenerateTrainerTraineesReportAsync(
            TrainerTraineesReportInputDto dto
        )
        {
            // ======================================================
            // Get trainee rows
            // ======================================================

            var rows =
                await _repository.GetTrainerTraineesReportRowsAsync(
                    dto.TrainerId,
                    dto.BatchId
                );


            // ======================================================
            // Reports folder
            // ======================================================

            var reportsFolder = Path.Combine(
               @"C:\NafadhStorage",
               "Reports"


            );

            Directory.CreateDirectory(reportsFolder);


            var generatedAt = DateTime.Now;


            var fileName =
                $"trainer-trainees-{dto.TrainerId}-{generatedAt:yyyyMMddHHmmssfff}.pdf";


            var fullPath =
                Path.Combine(
                    reportsFolder,
                    fileName
                );


            // ======================================================
            // Generate PDF
            // ======================================================

            var document =
                Document.Create(container =>
                {
                    container.Page(page =>
                    {
                        page.Size(
                            PageSizes.A4.Landscape()
                        );

                        page.Margin(30);


                        page.DefaultTextStyle(
                            style =>
                                style.FontSize(10)
                        );


                        // ------------------------------------------
                        // Header
                        // ------------------------------------------

                        page.Header()
                            .Column(header =>
                            {
                                header.Item()
                                    .AlignCenter()
                                    .Text("كشف تقييم ومتابعة المتدربين")
                                    .FontSize(20)
                                    .Bold();


                                header.Item()
                                    .PaddingTop(6)
                                    .AlignCenter()
                                    .Text(
                                        $"رقم المدرب: {dto.TrainerId}"
                                    )
                                    .FontSize(10);


                                if (dto.BatchId.HasValue)
                                {
                                    header.Item()
                                        .PaddingTop(3)
                                        .AlignCenter()
                                        .Text(
                                            $"رقم الدفعة: {dto.BatchId.Value}"
                                        )
                                        .FontSize(10);
                                }


                                header.Item()
                                    .PaddingTop(3)
                                    .AlignCenter()
                                    .Text(
                                        $"تاريخ التصدير: {generatedAt:yyyy-MM-dd HH:mm}"
                                    )
                                    .FontSize(10);
                            });


                        // ------------------------------------------
                        // Content
                        // ------------------------------------------

                        page.Content()
                            .PaddingVertical(20)
                            .Column(column =>
                            {
                                column.Spacing(10);


                                if (rows.Count == 0)
                                {
                                    column.Item()
                                        .AlignCenter()
                                        .PaddingTop(40)
                                        .Text(
                                            "لا يوجد متدربون متاحون لهذا الكشف."
                                        )
                                        .FontSize(14);

                                    return;
                                }


                                column.Item()
                                    .Table(table =>
                                    {
                                        // --------------------------
                                        // Columns
                                        // --------------------------

                                        table.ColumnsDefinition(
                                            columns =>
                                            {
                                                columns.ConstantColumn(70);
                                                columns.RelativeColumn(2);
                                                columns.RelativeColumn(2);
                                                columns.RelativeColumn(1.3f);
                                                columns.RelativeColumn(1.3f);
                                                columns.RelativeColumn(1.3f);
                                            }
                                        );


                                        // --------------------------
                                        // Table Header
                                        // --------------------------

                                        table.Header(header =>
                                        {
                                            header.Cell()
                                                .Border(1)
                                                .Padding(7)
                                                .AlignCenter()
                                                .Text("رقم التسجيل")
                                                .Bold();


                                            header.Cell()
                                                .Border(1)
                                                .Padding(7)
                                                .AlignCenter()
                                                .Text("المتدرب")
                                                .Bold();


                                            header.Cell()
                                                .Border(1)
                                                .Padding(7)
                                                .AlignCenter()
                                                .Text("الدفعة")
                                                .Bold();


                                            header.Cell()
                                                .Border(1)
                                                .Padding(7)
                                                .AlignCenter()
                                                .Text("المستوى التقني")
                                                .Bold();


                                            header.Cell()
                                                .Border(1)
                                                .Padding(7)
                                                .AlignCenter()
                                                .Text("نسبة الحضور")
                                                .Bold();


                                            header.Cell()
                                                .Border(1)
                                                .Padding(7)
                                                .AlignCenter()
                                                .Text("متوسط التقييم")
                                                .Bold();
                                        });


                                        // --------------------------
                                        // Table Rows
                                        // --------------------------

                                        foreach (var row in rows)
                                        {
                                            table.Cell()
                                                .Border(1)
                                                .Padding(6)
                                                .AlignCenter()
                                                .Text(
                                                    row.EnrollmentId.ToString()
                                                );


                                            table.Cell()
                                                .Border(1)
                                                .Padding(6)
                                                .AlignRight()
                                                .Text(
                                                    row.TraineeName ?? "—"
                                                );


                                            table.Cell()
                                                .Border(1)
                                                .Padding(6)
                                                .AlignRight()
                                                .Text(
                                                    row.BatchName ?? "—"
                                                );


                                            table.Cell()
                                                .Border(1)
                                                .Padding(6)
                                                .AlignCenter()
                                                .Text(
                                                    row.TechnicalLevel
                                                );


                                            table.Cell()
                                                .Border(1)
                                                .Padding(6)
                                                .AlignCenter()
                                                .Text(
                                                    $"{row.AttendancePercentage:0.#}%"
                                                );


                                            table.Cell()
                                                .Border(1)
                                                .Padding(6)
                                                .AlignCenter()
                                                .Text(
                                                    $"{row.AverageScore:0.#}%"
                                                );
                                        }
                                    });
                            });


                        // ------------------------------------------
                        // Footer
                        // ------------------------------------------

                        page.Footer()
                            .AlignCenter()
                            .Text(text =>
                            {
                                text.Span(
                                    "بوابة نفاذ - كشف المتدربين"
                                );
                            });
                    });
                });


            // ======================================================
            // Save PDF
            // ======================================================

            document.GeneratePdf(
                fullPath
            );


            var fileUrl = fullPath;



            // ======================================================
            // Save report record
            // ======================================================

            var report =
                new NFD_Report
                {
                    Type =
                        NFD_ReportType.Performance,

                    FiltersJson =
                        dto.BatchId.HasValue
                            ? $"BatchId: {dto.BatchId.Value}"
                            : null,

                    GeneratedAt =
                        generatedAt,

                    FileUrl =
                        fileUrl,

                    GeneratedByUserId =
                        dto.GeneratedByUserId
                };


            await _repository.AddReportAsync(
                report
            );


            // ======================================================
            // Return
            // ======================================================

            return new ReportOutputDTO
            {
                ReportId =
                    report.ReportId,

                Type =
                    report.Type,

                FiltersJson =
                    report.FiltersJson,

                GeneratedAt =
                    report.GeneratedAt,

                FileUrl =
                    report.FileUrl,

                GeneratedByUserId =
                    report.GeneratedByUserId
            };
        }

        // ==========================================================
        // GET Report/{id}
        // ==========================================================

        public async Task<ReportOutputDTO?> GetReportByIdAsync(int reportId)
        {
            var report = await _repository.GetReportByIdAsync(reportId);

            if (report == null)
                return null;

            return new ReportOutputDTO
            {
                ReportId = report.ReportId,
                Type = report.Type,
                FiltersJson = report.FiltersJson,
                GeneratedAt = report.GeneratedAt,
                FileUrl = report.FileUrl,
                GeneratedByUserId = report.GeneratedByUserId
            };
        }

        // ==========================================================
        // GET Report/{id}/download
        // ==========================================================

        public async Task<string?> DownloadReportAsync(int reportId)
        {
            var report = await _repository.GetReportByIdAsync(reportId);

            if (report == null)
                return null;

            return report.FileUrl;
        }
        // ==========================================================
        // Trainer Portal Report File
        // ==========================================================

        // Resolves Trainer Portal reports only from the configured
        // external reports folder without affecting shared reports.
        public async Task<string?>
            GetTrainerPortalReportFilePathAsync(
                int reportId
            )
        {
            var report =
                await GetReportByIdAsync(
                    reportId
                );


            if (
                report == null ||
                string.IsNullOrWhiteSpace(
                    report.FileUrl
                )
            )
            {
                return null;
            }


            var reportsFolder =
                _configuration[
                    "Storage:TrainerReportsPath"
                ];


            if (
                string.IsNullOrWhiteSpace(
                    reportsFolder
                )
            )
            {
                return null;
            }


            var reportsRoot =
                Path.GetFullPath(
                    reportsFolder
                );


            var filePath =
                Path.GetFullPath(
                    report.FileUrl
                );


            var rootWithSeparator =
                reportsRoot.TrimEnd(
                    Path.DirectorySeparatorChar,
                    Path.AltDirectorySeparatorChar
                )
                + Path.DirectorySeparatorChar;


            // Prevent reading files outside the configured
            // Trainer Portal reports directory.
            if (
                !filePath.StartsWith(
                    rootWithSeparator,
                    StringComparison.OrdinalIgnoreCase
                )
            )
            {
                return null;
            }


            // Keep this endpoint isolated to Trainer Portal PDFs.
            var fileName =
                Path.GetFileName(
                    filePath
                );


            if (
                !fileName.StartsWith(
                    "trainer-portal-report-",
                    StringComparison.OrdinalIgnoreCase
                )
            )
            {
                return null;
            }


            if (
                !File.Exists(
                    filePath
                )
            )
            {
                return null;
            }


            return filePath;
        }
        // ==========================================================
        // Analytics / Aggregation
        // ==========================================================

        public Task<DashboardChartsDTO> GetDashboardChartsAsync()
            => _repository.GetDashboardChartsAsync();

        public Task<BatchPerformanceReportDTO?> GetBatchPerformanceAsync(
            int batchId)
            => _repository.GetBatchPerformanceAsync(batchId);

        public Task<AttendanceReportDTO?> GetCompanyAttendanceReportAsync(
            int companyId)
            => _repository.GetCompanyAttendanceReportAsync(companyId);

        public Task<List<ChartPointDTO>> GetCompanyAttendanceChartAsync(
            int companyId)
            => _repository.GetCompanyAttendanceChartAsync(companyId);

        public Task<List<ChartPointDTO>> GetCompanyProgramDistributionAsync(
            int companyId)
            => _repository.GetCompanyProgramDistributionAsync(companyId);

        public Task<List<int>> GetCompanyTopPerformerTraineeIdsAsync(
            int companyId,
            int take)
            => _repository.GetCompanyTopPerformerTraineeIdsAsync(
                companyId,
                take
            );

        public Task<List<int>> GetCompanyAtRiskTraineeIdsAsync(
            int companyId,
            int take)
            => _repository.GetCompanyAtRiskTraineeIdsAsync(
                companyId,
                take
            );

        public Task<TrainerKpisDTO> GetTrainerKpisAsync(int trainerId)
            => _repository.GetTrainerKpisAsync(trainerId);
    }
}