// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services;
// Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;
using Nafadh_Backend.Repositories;
using Nafadh_Backend.DTOs;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Nafadh_Backend.Services
{
    public class ReportService : IReportService
    {
        private readonly IReportRepository _repository;
        private readonly IConfiguration _configuration;
        private readonly ITrainerService _trainerService;


        public ReportService(
            IReportRepository repository,
            IConfiguration configuration,
            ITrainerService trainerService
        )
        {
            _repository = repository;
            _configuration = configuration;
            _trainerService = trainerService;
        }


        // ==========================================================
        // GET Reports
        // ==========================================================

        public async Task<List<ReportOutputDTO>> GetReportsAsync(
            NFD_ReportType? type,
            int? userId
        )
        {
            var reports =
                await _repository.GetReportsAsync(
                    type,
                    userId
                );


            return reports
                .Select(r =>
                    new ReportOutputDTO
                    {
                        ReportId =
                            r.ReportId,

                        Type =
                            r.Type,

                        FiltersJson =
                            r.FiltersJson,

                        GeneratedAt =
                            r.GeneratedAt,

                        FileUrl =
                            r.FileUrl,

                        GeneratedByUserId =
                            r.GeneratedByUserId
                    }
                )
                .ToList();
        }


        // ==========================================================
        // TRAINER PORTAL REPORT
        //
        // This generator is used only by the Trainer Portal.
        // The shared report generator below remains unchanged.
        // ==========================================================

        public async Task<ReportOutputDTO>
            GenerateTrainerPortalReportAsync(
                ReportInputDTO dto
            )
        {
            // ======================================================
            // Validate Trainer
            // ======================================================

            if (!dto.TrainerId.HasValue)
            {
                throw new InvalidOperationException(
                    "TrainerId is required for Trainer Portal reports."
                );
            }


            var trainerId =
                dto.TrainerId.Value;


            // ======================================================
            // External Trainer Portal Reports Storage
            // ======================================================

            // Trainer Portal PDFs are stored outside the project
            // so generated files are never included in Git.
            var reportsFolder =
                _configuration[
                    "Storage:TrainerReportsPath"
                ];


            if (
                string.IsNullOrWhiteSpace(
                    reportsFolder
                )
            )
            {
                throw new InvalidOperationException(
                    "Trainer reports storage path is not configured."
                );
            }


            Directory.CreateDirectory(
                reportsFolder
            );


            var generatedAt =
                DateTime.Now;


            var fileName =
                $"trainer-portal-report-{trainerId}-{generatedAt:yyyyMMddHHmmssfff}.pdf";


            var fullPath =
                Path.Combine(
                    reportsFolder,
                    fileName
                );


            // ======================================================
            // Trainer Information
            // ======================================================

            var trainer =
                await _trainerService.GetByIdAsync(
                    trainerId
                );


            var trainerName =
                !string.IsNullOrWhiteSpace(
                    trainer?.FullName
                )
                    ? trainer.FullName
                    : "غير محدد";


            // ======================================================
            // Trainer KPIs
            // ======================================================

            var kpis =
                await _repository
                    .GetTrainerKpisAsync(
                        trainerId
                    );


            // ======================================================
            // Attendance Rows
            //
            // Loaded only when the trainer requests
            // an Attendance report.
            // ======================================================

            var attendanceRows =
    (
        dto.Type ==
            NFD_ReportType.Attendance ||

        dto.Type ==
            NFD_ReportType.Custom
    )
        ? await _repository
            .GetTrainerTraineesReportRowsAsync(
                trainerId,
                null
            )
        : null;


            // ======================================================
            // Arabic Report Type
            // ======================================================

            var reportTypeName =
                dto.Type switch
                {
                    NFD_ReportType.Attendance =>
                        "تقرير الحضور والغياب",

                    NFD_ReportType.Performance =>
                      "تقرير أداء الدفعات والمهام",

                    NFD_ReportType.Financial =>
                        "التقرير المالي",

                    NFD_ReportType.Enrollment =>
                        "تقرير التسجيل",

                    NFD_ReportType.Custom =>
                     "التقرير الشامل للأداء التدريبي",

                    _ =>
                        "تقرير المدرب"
                };


            // ======================================================
            // Generate Trainer Portal PDF
            // ======================================================

            var document =
                Document.Create(container =>
                {
                    container.Page(page =>
                    {
                        page.Size(
                            PageSizes.A4
                        );


                        page.Margin(35);


                        page.DefaultTextStyle(
                            style =>
                                style.FontSize(11)
                        );


                        // ===========================================
                        // HEADER
                        // ===========================================

                        page.Header()
                            .Background(
                                "#003B82"
                            )
                            .Padding(20)
                            .Column(header =>
                            {
                                header.Item()
                                    .AlignCenter()
                                    .Text(
                                        reportTypeName
                                    )
                                    .FontSize(23)
                                    .Bold()
                                    .FontColor(
                                        Colors.White
                                    );


                                header.Item()
                                    .PaddingTop(5)
                                    .AlignCenter()
                                    .Text(
                                        "بوابة نفاذ للتدريب والتطوير"
                                    )
                                    .FontSize(10)
                                    .FontColor(
                                        Colors.White
                                    );
                            });


                        // ===========================================
                        // CONTENT
                        // ===========================================

                        page.Content()
                            .PaddingVertical(24)
                            .Column(column =>
                            {
                                column.Spacing(18);


                                // ===================================
                                // REPORT INFORMATION
                                // ===================================

                                column.Item()
                                    .Border(1)
                                    .BorderColor(
                                        Colors.Grey.Lighten2
                                    )
                                    .Padding(16)
                                    .Column(info =>
                                    {
                                        info.Spacing(9);


                                        info.Item()
                                            .AlignRight()
                                            .Text(
                                                "بيانات التقرير"
                                            )
                                            .FontSize(16)
                                            .Bold()
                                            .FontColor(
                                                "#003B82"
                                            );


                                        info.Item()
                                            .LineHorizontal(1)
                                            .LineColor(
                                                Colors.Grey.Lighten2
                                            );


                                        // Real trainer name instead of TrainerId.
                                        info.Item()
                                            .AlignRight()
                                            .Text(text =>
                                            {
                                                text.Span(
                                                    "اسم المدرب: "
                                                )
                                                .SemiBold();


                                                text.Span(
                                                    trainerName
                                                );
                                            });


                                        info.Item()
                                            .AlignRight()
                                            .Text(text =>
                                            {
                                                text.Span(
                                                    "نوع التقرير: "
                                                )
                                                .SemiBold();


                                                text.Span(
                                                    reportTypeName
                                                );
                                            });


                                        info.Item()
                                            .AlignRight()
                                            .Text(text =>
                                            {
                                                text.Span(
                                                    "تاريخ التقرير: "
                                                )
                                                .SemiBold();


                                                text.Span(
                                                    generatedAt.ToString(
                                                        "yyyy-MM-dd"
                                                    )
                                                );
                                            });


                                        info.Item()
                                            .AlignRight()
                                            .Text(text =>
                                            {
                                                text.Span(
                                                    "وقت الإنشاء: "
                                                )
                                                .SemiBold();


                                                text.Span(
                                                    generatedAt.ToString(
                                                        "HH:mm"
                                                    )
                                                );
                                            });
                                    });


                                // ===================================
                                // REPORT CONTENT BY TYPE
                                // ===================================

                                if (kpis != null)
                                {
                                    // ==================================================
                                    // ATTENDANCE REPORT
                                    // Attendance information only.
                                    // ==================================================

                                    if (
                                        dto.Type ==
                                        NFD_ReportType.Attendance
                                    )
                                    {
                                        column.Item()
                                            .AlignRight()
                                            .Text(
                                                "ملخص الحضور والغياب"
                                            )
                                            .FontSize(18)
                                            .Bold()
                                            .FontColor(
                                                "#0F172A"
                                            );


                                        column.Item()
                                            .Background(
                                                "#F0F9FF"
                                            )
                                            .Border(1)
                                            .BorderColor(
                                                "#BAE6FD"
                                            )
                                            .Padding(16)
                                            .Column(card =>
                                            {
                                                card.Item()
                                                    .AlignCenter()
                                                    .Text(
                                                        "نسبة الحضور العامة"
                                                    )
                                                    .FontSize(10)
                                                    .FontColor(
                                                        "#64748B"
                                                    );


                                                card.Item()
                                                    .PaddingTop(6)
                                                    .AlignCenter()
                                                    .Text(
                                                        $"{kpis.AttendanceRate:0.#}%"
                                                    )
                                                    .FontSize(24)
                                                    .Bold()
                                                    .FontColor(
                                                        "#003B82"
                                                    );
                                            });


                                        column.Item()
                                            .Border(1)
                                            .BorderColor(
                                                Colors.Grey.Lighten2
                                            )
                                            .Padding(16)
                                            .Column(details =>
                                            {
                                                details.Spacing(10);


                                                details.Item()
                                                    .AlignRight()
                                                    .Text(
                                                        "تفاصيل الحضور"
                                                    )
                                                    .FontSize(15)
                                                    .Bold();


                                                details.Item()
                                                    .LineHorizontal(1)
                                                    .LineColor(
                                                        Colors.Grey.Lighten2
                                                    );


                                                details.Item()
                                                    .AlignRight()
                                                    .Text(
                                                        $"نسبة الحضور العامة: {kpis.AttendanceRate:0.#}%"
                                                    );
                                            });
                                    }


                                    // ==================================================
                                    // PERFORMANCE REPORT
                                    // Tasks and technical grades only.
                                    // ==================================================

                                    else if (
                                        dto.Type ==
                                        NFD_ReportType.Performance
                                    )
                                    {
                                        column.Item()
                                            .AlignRight()
                                            .Text(
                                                "ملخص أداء الدفعات والمهام"
                                            )
                                            .FontSize(18)
                                            .Bold()
                                            .FontColor(
                                                "#0F172A"
                                            );


                                        column.Item()
                                            .Row(row =>
                                            {
                                                row.Spacing(10);


                                                row.RelativeItem()
                                                    .Background(
                                                        "#F0F9FF"
                                                    )
                                                    .Border(1)
                                                    .BorderColor(
                                                        "#BAE6FD"
                                                    )
                                                    .Padding(14)
                                                    .Column(card =>
                                                    {
                                                        card.Item()
                                                            .AlignCenter()
                                                            .Text(
                                                                "إنجاز المهام"
                                                            )
                                                            .FontSize(10)
                                                            .FontColor(
                                                                "#64748B"
                                                            );


                                                        card.Item()
                                                            .PaddingTop(6)
                                                            .AlignCenter()
                                                            .Text(
                                                                $"{kpis.TaskCompletionRate:0.#}%"
                                                            )
                                                            .FontSize(21)
                                                            .Bold()
                                                            .FontColor(
                                                                "#003B82"
                                                            );
                                                    });


                                                row.RelativeItem()
                                                    .Background(
                                                        "#F0F9FF"
                                                    )
                                                    .Border(1)
                                                    .BorderColor(
                                                        "#BAE6FD"
                                                    )
                                                    .Padding(14)
                                                    .Column(card =>
                                                    {
                                                        card.Item()
                                                            .AlignCenter()
                                                            .Text(
                                                                "متوسط الدرجات الفنية"
                                                            )
                                                            .FontSize(10)
                                                            .FontColor(
                                                                "#64748B"
                                                            );


                                                        card.Item()
                                                            .PaddingTop(6)
                                                            .AlignCenter()
                                                            .Text(
                                                                $"{kpis.AvgTechnicalGrade:0.#}"
                                                            )
                                                            .FontSize(21)
                                                            .Bold()
                                                            .FontColor(
                                                                "#003B82"
                                                            );


                                                        card.Item()
                                                            .AlignCenter()
                                                            .Text(
                                                                "من 100"
                                                            )
                                                            .FontSize(8)
                                                            .FontColor(
                                                                "#94A3B8"
                                                            );
                                                    });
                                            });


                                        column.Item()
                                            .Border(1)
                                            .BorderColor(
                                                Colors.Grey.Lighten2
                                            )
                                            .Padding(16)
                                            .Column(details =>
                                            {
                                                details.Spacing(10);


                                                details.Item()
                                                    .AlignRight()
                                                    .Text(
                                                        "تفاصيل أداء الدفعات والمهام"
                                                    )
                                                    .FontSize(15)
                                                    .Bold();


                                                details.Item()
                                                    .LineHorizontal(1)
                                                    .LineColor(
                                                        Colors.Grey.Lighten2
                                                    );


                                                details.Item()
                                                    .AlignRight()
                                                    .Text(
                                                        $"معدل إنجاز المهام: {kpis.TaskCompletionRate:0.#}%"
                                                    );


                                                details.Item()
                                                    .AlignRight()
                                                    .Text(
                                                        $"متوسط الدرجات الفنية: {kpis.AvgTechnicalGrade:0.#} من 100"
                                                    );
                                            });
                                    }


                                    // ==================================================
                                    // COMPREHENSIVE REPORT
                                    // Attendance + tasks + technical grades.
                                    // ==================================================

                                    else if (
                                        dto.Type ==
                                        NFD_ReportType.Custom
                                    )
                                    {
                                        column.Item()
                                            .AlignRight()
                                            .Text(
                                                "ملخص الأداء التدريبي"
                                            )
                                            .FontSize(18)
                                            .Bold()
                                            .FontColor(
                                                "#0F172A"
                                            );


                                        column.Item()
                                            .Row(row =>
                                            {
                                                row.Spacing(10);


                                                // Attendance
                                                row.RelativeItem()
                                                    .Background(
                                                        "#F0F9FF"
                                                    )
                                                    .Border(1)
                                                    .BorderColor(
                                                        "#BAE6FD"
                                                    )
                                                    .Padding(14)
                                                    .Column(card =>
                                                    {
                                                        card.Item()
                                                            .AlignCenter()
                                                            .Text(
                                                                "الحضور"
                                                            )
                                                            .FontSize(10)
                                                            .FontColor(
                                                                "#64748B"
                                                            );


                                                        card.Item()
                                                            .PaddingTop(6)
                                                            .AlignCenter()
                                                            .Text(
                                                                $"{kpis.AttendanceRate:0.#}%"
                                                            )
                                                            .FontSize(21)
                                                            .Bold()
                                                            .FontColor(
                                                                "#003B82"
                                                            );
                                                    });


                                                // Tasks
                                                row.RelativeItem()
                                                    .Background(
                                                        "#F0F9FF"
                                                    )
                                                    .Border(1)
                                                    .BorderColor(
                                                        "#BAE6FD"
                                                    )
                                                    .Padding(14)
                                                    .Column(card =>
                                                    {
                                                        card.Item()
                                                            .AlignCenter()
                                                            .Text(
                                                                "إنجاز المهام"
                                                            )
                                                            .FontSize(10)
                                                            .FontColor(
                                                                "#64748B"
                                                            );


                                                        card.Item()
                                                            .PaddingTop(6)
                                                            .AlignCenter()
                                                            .Text(
                                                                $"{kpis.TaskCompletionRate:0.#}%"
                                                            )
                                                            .FontSize(21)
                                                            .Bold()
                                                            .FontColor(
                                                                "#003B82"
                                                            );
                                                    });


                                                // Technical Grade
                                                row.RelativeItem()
                                                    .Background(
                                                        "#F0F9FF"
                                                    )
                                                    .Border(1)
                                                    .BorderColor(
                                                        "#BAE6FD"
                                                    )
                                                    .Padding(14)
                                                    .Column(card =>
                                                    {
                                                        card.Item()
                                                            .AlignCenter()
                                                            .Text(
                                                                "التقييم الفني"
                                                            )
                                                            .FontSize(10)
                                                            .FontColor(
                                                                "#64748B"
                                                            );


                                                        card.Item()
                                                            .PaddingTop(6)
                                                            .AlignCenter()
                                                            .Text(
                                                                $"{kpis.AvgTechnicalGrade:0.#}"
                                                            )
                                                            .FontSize(21)
                                                            .Bold()
                                                            .FontColor(
                                                                "#003B82"
                                                            );


                                                        card.Item()
                                                            .AlignCenter()
                                                            .Text(
                                                                "من 100"
                                                            )
                                                            .FontSize(8)
                                                            .FontColor(
                                                                "#94A3B8"
                                                            );
                                                    });
                                            });


                                        column.Item()
                                            .Border(1)
                                            .BorderColor(
                                                Colors.Grey.Lighten2
                                            )
                                            .Padding(16)
                                            .Column(details =>
                                            {
                                                details.Spacing(10);


                                                details.Item()
                                                    .AlignRight()
                                                    .Text(
                                                        "تفاصيل مؤشرات الأداء"
                                                    )
                                                    .FontSize(15)
                                                    .Bold();


                                                details.Item()
                                                    .LineHorizontal(1)
                                                    .LineColor(
                                                        Colors.Grey.Lighten2
                                                    );


                                                details.Item()
                                                    .AlignRight()
                                                    .Text(
                                                        $"نسبة الحضور العامة: {kpis.AttendanceRate:0.#}%"
                                                    );


                                                details.Item()
                                                    .AlignRight()
                                                    .Text(
                                                        $"معدل إنجاز المهام: {kpis.TaskCompletionRate:0.#}%"
                                                    );


                                                details.Item()
                                                    .AlignRight()
                                                    .Text(
                                                        $"متوسط الدرجات الفنية: {kpis.AvgTechnicalGrade:0.#} من 100"
                                                    );
                                            });
                                    }
                                }

                                // ===================================
                                // ATTENDANCE REPORT DETAILS
                                // ===================================
                                if (
    (
        dto.Type ==
            NFD_ReportType.Attendance ||

        dto.Type ==
            NFD_ReportType.Custom
    ) &&
    attendanceRows != null
)
                                {
                                    column.Item()
                                        .AlignRight()
                                        .Text(
                                            "تفاصيل حضور المتدربين"
                                        )
                                        .FontSize(16)
                                        .Bold()
                                        .FontColor(
                                            "#003B82"
                                        );


                                    if (
                                        attendanceRows.Count == 0
                                    )
                                    {
                                        column.Item()
                                            .Background(
                                                "#F8FAFC"
                                            )
                                            .Border(1)
                                            .BorderColor(
                                                "#E2E8F0"
                                            )
                                            .Padding(14)
                                            .AlignCenter()
                                            .Text(
                                                "لا توجد بيانات حضور مسجلة للدفعات التابعة لهذا المدرب."
                                            )
                                            .FontSize(10)
                                            .FontColor(
                                                "#64748B"
                                            );
                                    }
                                    else
                                    {
                                        column.Item()
                                            .Table(table =>
                                            {
                                                // ===================
                                                // Columns
                                                // ===================

                                                table.ColumnsDefinition(
                                                    columns =>
                                                    {
                                                        columns.RelativeColumn(
                                                            2.2f
                                                        );

                                                        columns.RelativeColumn(
                                                            2
                                                        );

                                                        columns.RelativeColumn(
                                                            1.2f
                                                        );

                                                        columns.RelativeColumn(
                                                            1.4f
                                                        );
                                                    }
                                                );


                                                // ===================
                                                // Header
                                                // ===================

                                                table.Header(header =>
                                                {
                                                    header.Cell()
                                                        .Background(
                                                            "#003B82"
                                                        )
                                                        .Padding(8)
                                                        .AlignCenter()
                                                        .Text(
                                                            "المتدرب"
                                                        )
                                                        .FontColor(
                                                            Colors.White
                                                        )
                                                        .Bold();


                                                    header.Cell()
                                                        .Background(
                                                            "#003B82"
                                                        )
                                                        .Padding(8)
                                                        .AlignCenter()
                                                        .Text(
                                                            "الدفعة"
                                                        )
                                                        .FontColor(
                                                            Colors.White
                                                        )
                                                        .Bold();


                                                    header.Cell()
                                                        .Background(
                                                            "#003B82"
                                                        )
                                                        .Padding(8)
                                                        .AlignCenter()
                                                        .Text(
                                                            "نسبة الحضور"
                                                        )
                                                        .FontColor(
                                                            Colors.White
                                                        )
                                                        .Bold();


                                                    header.Cell()
                                                        .Background(
                                                            "#003B82"
                                                        )
                                                        .Padding(8)
                                                        .AlignCenter()
                                                        .Text(
                                                            "الحالة"
                                                        )
                                                        .FontColor(
                                                            Colors.White
                                                        )
                                                        .Bold();
                                                });


                                                // ===================
                                                // Attendance Rows
                                                // ===================

                                                foreach (
                                                    var attendance
                                                    in attendanceRows
                                                )
                                                {
                                                    var attendanceStatus =
                                                        attendance
                                                            .AttendancePercentage >= 90
                                                            ? "ممتاز"
                                                            : attendance
                                                                .AttendancePercentage >= 75
                                                                ? "جيد"
                                                                : "يحتاج متابعة";


                                                    table.Cell()
                                                        .BorderBottom(1)
                                                        .BorderColor(
                                                            Colors.Grey.Lighten2
                                                        )
                                                        .Padding(8)
                                                        .AlignRight()
                                                        .Text(
                                                            attendance
                                                                .TraineeName
                                                            ?? "—"
                                                        );


                                                    table.Cell()
                                                        .BorderBottom(1)
                                                        .BorderColor(
                                                            Colors.Grey.Lighten2
                                                        )
                                                        .Padding(8)
                                                        .AlignRight()
                                                        .Text(
                                                            attendance
                                                                .BatchName
                                                            ?? "—"
                                                        );


                                                    table.Cell()
                                                        .BorderBottom(1)
                                                        .BorderColor(
                                                            Colors.Grey.Lighten2
                                                        )
                                                        .Padding(8)
                                                        .AlignCenter()
                                                        .Text(
                                                            $"{attendance.AttendancePercentage:0.#}%"
                                                        )
                                                        .Bold();


                                                    table.Cell()
                                                        .BorderBottom(1)
                                                        .BorderColor(
                                                            Colors.Grey.Lighten2
                                                        )
                                                        .Padding(8)
                                                        .AlignCenter()
                                                        .Text(
                                                            attendanceStatus
                                                        );
                                                }
                                            });
                                    }
                                }


                                // ===================================
                                // SYSTEM NOTE
                                // ===================================

                                column.Item()
                                    .Background(
                                        "#F8FAFC"
                                    )
                                    .Border(1)
                                    .BorderColor(
                                        "#E2E8F0"
                                    )
                                    .Padding(12)
                                    .AlignRight()
                                    .Text(
                                        "تم إعداد هذا التقرير تلقائيًا اعتمادًا على البيانات المسجلة في بوابة نفاذ."
                                    )
                                    .FontSize(9)
                                    .FontColor(
                                        "#64748B"
                                    );


                                // FiltersJson contains internal
                                // Trainer Portal metadata and is
                                // intentionally not shown in the PDF.
                            });


                        // ===========================================
                        // FOOTER
                        // ===========================================

                        page.Footer()
                            .PaddingTop(10)
                            .Row(row =>
                            {
                                row.RelativeItem()
                                    .AlignLeft()
                                    .Text(
                                        generatedAt.ToString(
                                            "yyyy-MM-dd"
                                        )
                                    )
                                    .FontSize(8)
                                    .FontColor(
                                        "#94A3B8"
                                    );


                                row.RelativeItem()
                                    .AlignRight()
                                    .Text(
                                        "بوابة نفاذ للتدريب والتطوير"
                                    )
                                    .FontSize(8)
                                    .FontColor(
                                        "#94A3B8"
                                    );
                            });
                    });
                });


            // ======================================================
            // Save PDF
            // ======================================================

            document.GeneratePdf(
                fullPath
            );


            // The Trainer Portal stores the absolute physical path
            // because its dedicated endpoint validates and reads it.
            var fileUrl =
                fullPath;


            // ======================================================
            // Save Report Metadata
            // ======================================================

            var report =
                new NFD_Report
                {
                    Type =
                        dto.Type,

                    FiltersJson =
                        dto.FiltersJson,

                    GeneratedAt =
                        generatedAt,

                    FileUrl =
                        fileUrl,

                    GeneratedByUserId =
                        dto.GeneratedByUserId
                };


            await _repository.AddReportAsync(
                report
            );


            // ======================================================
            // Return
            // ======================================================

            return new ReportOutputDTO
            {
                ReportId =
                    report.ReportId,

                Type =
                    report.Type,

                FiltersJson =
                    report.FiltersJson,

                GeneratedAt =
                    report.GeneratedAt,

                FileUrl =
                    report.FileUrl,

                GeneratedByUserId =
                    report.GeneratedByUserId
            };
        }


        // ==========================================================
        // SHARED PDF REPORT
        //
        // Keep this unchanged.
        // Other portals may depend on this behavior.
        // ==========================================================

        public async Task<ReportOutputDTO>
            GenerateReportAsync(
                ReportInputDTO dto
            )
        {
            // مجلد حفظ التقارير
            var reportsFolder =
                Path.Combine(
                    Directory.GetCurrentDirectory(),
                    "wwwroot",
                    "reports"
                );


            // إنشاء المجلد إذا لم يكن موجوداً
            Directory.CreateDirectory(
                reportsFolder
            );


            var generatedAt =
                DateTime.Now;


            // اسم فريد للملف
            var fileName =
                $"trainer-report-{dto.TrainerId ?? 0}-{generatedAt:yyyyMMddHHmmssfff}.pdf";


            var fullPath =
                Path.Combine(
                    reportsFolder,
                    fileName
                );


            // ======================================================
            // جلب مؤشرات المدرب
            // ======================================================

            TrainerKpisDTO? kpis =
                null;


            if (dto.TrainerId.HasValue)
            {
                kpis =
                    await _repository.GetTrainerKpisAsync(
                        dto.TrainerId.Value
                    );
            }


            // ======================================================
            // إنشاء ملف PDF
            // ======================================================

            var document =
                Document.Create(container =>
                {
                    container.Page(page =>
                    {
                        page.Size(
                            PageSizes.A4
                        );


                        page.Margin(
                            30
                        );


                        page.DefaultTextStyle(
                            style =>
                                style.FontSize(12)
                        );


                        // ---------------- Header ----------------

                        page.Header()
                            .AlignCenter()
                            .Text(
                                "تقرير المدرب"
                            )
                            .FontSize(22)
                            .Bold();


                        // ---------------- Content ----------------

                        page.Content()
                            .PaddingVertical(20)
                            .Column(column =>
                            {
                                column.Spacing(
                                    12
                                );


                                column.Item()
                                    .AlignRight()
                                    .Text(
                                        $"نوع التقرير: {dto.Type}"
                                    );


                                if (
                                    dto.TrainerId.HasValue
                                )
                                {
                                    column.Item()
                                        .AlignRight()
                                        .Text(
                                            $"رقم المدرب: {dto.TrainerId.Value}"
                                        );
                                }


                                column.Item()
                                    .AlignRight()
                                    .Text(
                                        $"تاريخ الإنشاء: {generatedAt:yyyy-MM-dd HH:mm}"
                                    );


                                // ----------------------------------
                                // KPIs
                                // ----------------------------------

                                if (kpis != null)
                                {
                                    column.Item()
                                        .PaddingTop(15)
                                        .AlignRight()
                                        .Text(
                                            "مؤشرات الأداء"
                                        )
                                        .FontSize(17)
                                        .Bold();


                                    column.Item()
                                        .AlignRight()
                                        .Text(
                                            $"نسبة الحضور العامة: {kpis.AttendanceRate}%"
                                        );


                                    column.Item()
                                        .AlignRight()
                                        .Text(
                                            $"معدل إنجاز المهام: {kpis.TaskCompletionRate}%"
                                        );


                                    column.Item()
                                        .AlignRight()
                                        .Text(
                                            $"متوسط الدرجات الفنية: {kpis.AvgTechnicalGrade} / 100"
                                        );
                                }


                                // ----------------------------------
                                // Filters
                                // ----------------------------------

                                if (
                                    !string.IsNullOrWhiteSpace(
                                        dto.FiltersJson
                                    )
                                )
                                {
                                    column.Item()
                                        .PaddingTop(15)
                                        .AlignRight()
                                        .Text(
                                            "بيانات التقرير"
                                        )
                                        .FontSize(15)
                                        .Bold();


                                    column.Item()
                                        .AlignRight()
                                        .Text(
                                            dto.FiltersJson
                                        );
                                }
                            });


                        // ---------------- Footer ----------------

                        page.Footer()
                            .AlignCenter()
                            .Text(text =>
                            {
                                text.Span(
                                    "بوابة نفاذ - "
                                );

                                text.Span(
                                    "تقرير المدرب"
                                );
                            });
                    });
                });


            // حفظ PDF داخل wwwroot/reports
            document.GeneratePdf(
                fullPath
            );


            // نخزن المسار النسبي فقط في قاعدة البيانات
            var fileUrl =
                $"reports/{fileName}";


            // ======================================================
            // حفظ سجل التقرير في قاعدة البيانات
            // ======================================================

            var report =
                new NFD_Report
                {
                    Type =
                        dto.Type,

                    FiltersJson =
                        dto.FiltersJson,

                    GeneratedAt =
                        generatedAt,

                    FileUrl =
                        fileUrl,

                    GeneratedByUserId =
                        dto.GeneratedByUserId
                };


            await _repository.AddReportAsync(
                report
            );


            // ======================================================
            // Return
            // ======================================================

            return new ReportOutputDTO
            {
                ReportId =
                    report.ReportId,

                Type =
                    report.Type,

                FiltersJson =
                    report.FiltersJson,

                GeneratedAt =
                    report.GeneratedAt,

                FileUrl =
                    report.FileUrl,

                GeneratedByUserId =
                    report.GeneratedByUserId
            };
        }


        // ==========================================================
        // Generate Trainer Trainees PDF Report
        //
        // Existing report used by another Trainer feature.
        // Kept separate from Trainer Portal report generation.
        // ==========================================================

        public async Task<ReportOutputDTO>
            GenerateTrainerTraineesReportAsync(
                TrainerTraineesReportInputDto dto
            )
        {
            // ======================================================
            // Get Trainee Rows
            // ======================================================

            var rows =
                await _repository
                    .GetTrainerTraineesReportRowsAsync(
                        dto.TrainerId,
                        dto.BatchId
                    );


            // ======================================================
            // Reports Folder
            // ======================================================

            var reportsFolder =
                Path.Combine(
                    @"C:\NafadhStorage",
                    "Reports"
                );


            Directory.CreateDirectory(
                reportsFolder
            );


            var generatedAt =
                DateTime.Now;


            var fileName =
                $"trainer-trainees-{dto.TrainerId}-{generatedAt:yyyyMMddHHmmssfff}.pdf";


            var fullPath =
                Path.Combine(
                    reportsFolder,
                    fileName
                );


            // ======================================================
            // Generate PDF
            // ======================================================

            var document =
                Document.Create(container =>
                {
                    container.Page(page =>
                    {
                        page.Size(
                            PageSizes.A4.Landscape()
                        );


                        page.Margin(
                            30
                        );


                        page.DefaultTextStyle(
                            style =>
                                style.FontSize(10)
                        );


                        // ------------------------------------------
                        // Header
                        // ------------------------------------------

                        page.Header()
                            .Column(header =>
                            {
                                header.Item()
                                    .AlignCenter()
                                    .Text(
                                        "كشف تقييم ومتابعة المتدربين"
                                    )
                                    .FontSize(20)
                                    .Bold();


                                header.Item()
                                    .PaddingTop(6)
                                    .AlignCenter()
                                    .Text(
                                        $"رقم المدرب: {dto.TrainerId}"
                                    )
                                    .FontSize(10);


                                if (
                                    dto.BatchId.HasValue
                                )
                                {
                                    header.Item()
                                        .PaddingTop(3)
                                        .AlignCenter()
                                        .Text(
                                            $"رقم الدفعة: {dto.BatchId.Value}"
                                        )
                                        .FontSize(10);
                                }


                                header.Item()
                                    .PaddingTop(3)
                                    .AlignCenter()
                                    .Text(
                                        $"تاريخ التصدير: {generatedAt:yyyy-MM-dd HH:mm}"
                                    )
                                    .FontSize(10);
                            });


                        // ------------------------------------------
                        // Content
                        // ------------------------------------------

                        page.Content()
                            .PaddingVertical(20)
                            .Column(column =>
                            {
                                column.Spacing(
                                    10
                                );


                                if (
                                    rows.Count == 0
                                )
                                {
                                    column.Item()
                                        .AlignCenter()
                                        .PaddingTop(40)
                                        .Text(
                                            "لا يوجد متدربون متاحون لهذا الكشف."
                                        )
                                        .FontSize(14);


                                    return;
                                }


                                column.Item()
                                    .Table(table =>
                                    {
                                        // --------------------------
                                        // Columns
                                        // --------------------------

                                        table.ColumnsDefinition(
                                            columns =>
                                            {
                                                columns.ConstantColumn(
                                                    70
                                                );

                                                columns.RelativeColumn(
                                                    2
                                                );

                                                columns.RelativeColumn(
                                                    2
                                                );

                                                columns.RelativeColumn(
                                                    1.3f
                                                );

                                                columns.RelativeColumn(
                                                    1.3f
                                                );

                                                columns.RelativeColumn(
                                                    1.3f
                                                );
                                            }
                                        );


                                        // --------------------------
                                        // Table Header
                                        // --------------------------

                                        table.Header(header =>
                                        {
                                            header.Cell()
                                                .Border(1)
                                                .Padding(7)
                                                .AlignCenter()
                                                .Text(
                                                    "رقم التسجيل"
                                                )
                                                .Bold();


                                            header.Cell()
                                                .Border(1)
                                                .Padding(7)
                                                .AlignCenter()
                                                .Text(
                                                    "المتدرب"
                                                )
                                                .Bold();


                                            header.Cell()
                                                .Border(1)
                                                .Padding(7)
                                                .AlignCenter()
                                                .Text(
                                                    "الدفعة"
                                                )
                                                .Bold();


                                            header.Cell()
                                                .Border(1)
                                                .Padding(7)
                                                .AlignCenter()
                                                .Text(
                                                    "المستوى التقني"
                                                )
                                                .Bold();


                                            header.Cell()
                                                .Border(1)
                                                .Padding(7)
                                                .AlignCenter()
                                                .Text(
                                                    "نسبة الحضور"
                                                )
                                                .Bold();


                                            header.Cell()
                                                .Border(1)
                                                .Padding(7)
                                                .AlignCenter()
                                                .Text(
                                                    "متوسط التقييم"
                                                )
                                                .Bold();
                                        });


                                        // --------------------------
                                        // Table Rows
                                        // --------------------------

                                        foreach (
                                            var row
                                            in rows
                                        )
                                        {
                                            table.Cell()
                                                .Border(1)
                                                .Padding(6)
                                                .AlignCenter()
                                                .Text(
                                                    row.EnrollmentId
                                                        .ToString()
                                                );


                                            table.Cell()
                                                .Border(1)
                                                .Padding(6)
                                                .AlignRight()
                                                .Text(
                                                    row.TraineeName
                                                    ?? "—"
                                                );


                                            table.Cell()
                                                .Border(1)
                                                .Padding(6)
                                                .AlignRight()
                                                .Text(
                                                    row.BatchName
                                                    ?? "—"
                                                );


                                            table.Cell()
                                                .Border(1)
                                                .Padding(6)
                                                .AlignCenter()
                                                .Text(
                                                    row.TechnicalLevel
                                                );


                                            table.Cell()
                                                .Border(1)
                                                .Padding(6)
                                                .AlignCenter()
                                                .Text(
                                                    $"{row.AttendancePercentage:0.#}%"
                                                );


                                            table.Cell()
                                                .Border(1)
                                                .Padding(6)
                                                .AlignCenter()
                                                .Text(
                                                    $"{row.AverageScore:0.#}%"
                                                );
                                        }
                                    });
                            });


                        // ------------------------------------------
                        // Footer
                        // ------------------------------------------

                        page.Footer()
                            .AlignCenter()
                            .Text(text =>
                            {
                                text.Span(
                                    "بوابة نفاذ - كشف المتدربين"
                                );
                            });
                    });
                });


            // ======================================================
            // Save PDF
            // ======================================================

            document.GeneratePdf(
                fullPath
            );


            var fileUrl =
                fullPath;


            // ======================================================
            // Save Report Record
            // ======================================================

            var report =
                new NFD_Report
                {
                    Type =
                        NFD_ReportType.Performance,

                    FiltersJson =
                        dto.BatchId.HasValue
                            ? $"BatchId: {dto.BatchId.Value}"
                            : null,

                    GeneratedAt =
                        generatedAt,

                    FileUrl =
                        fileUrl,

                    GeneratedByUserId =
                        dto.GeneratedByUserId
                };


            await _repository.AddReportAsync(
                report
            );


            // ======================================================
            // Return
            // ======================================================

            return new ReportOutputDTO
            {
                ReportId =
                    report.ReportId,

                Type =
                    report.Type,

                FiltersJson =
                    report.FiltersJson,

                GeneratedAt =
                    report.GeneratedAt,

                FileUrl =
                    report.FileUrl,

                GeneratedByUserId =
                    report.GeneratedByUserId
            };
        }


        // ==========================================================
        // GET Report/{id}
        // ==========================================================

        public async Task<ReportOutputDTO?>
            GetReportByIdAsync(
                int reportId
            )
        {
            var report =
                await _repository
                    .GetReportByIdAsync(
                        reportId
                    );


            if (report == null)
            {
                return null;
            }


            return new ReportOutputDTO
            {
                ReportId =
                    report.ReportId,

                Type =
                    report.Type,

                FiltersJson =
                    report.FiltersJson,

                GeneratedAt =
                    report.GeneratedAt,

                FileUrl =
                    report.FileUrl,

                GeneratedByUserId =
                    report.GeneratedByUserId
            };
        }


        // ==========================================================
        // SHARED Report Download
        //
        // Do not change. Existing portals may use this.
        // ==========================================================

        public async Task<string?>
            DownloadReportAsync(
                int reportId
            )
        {
            var report =
                await _repository
                    .GetReportByIdAsync(
                        reportId
                    );


            if (report == null)
            {
                return null;
            }


            return report.FileUrl;
        }


        // ==========================================================
        // Trainer Portal Report File
        // ==========================================================

        // Resolves Trainer Portal reports only from the configured
        // external folder without affecting shared report downloads.
        public async Task<string?>
            GetTrainerPortalReportFilePathAsync(
                int reportId
            )
        {
            var report =
                await GetReportByIdAsync(
                    reportId
                );


            if (
                report == null ||
                string.IsNullOrWhiteSpace(
                    report.FileUrl
                )
            )
            {
                return null;
            }


            var reportsFolder =
                _configuration[
                    "Storage:TrainerReportsPath"
                ];


            if (
                string.IsNullOrWhiteSpace(
                    reportsFolder
                )
            )
            {
                return null;
            }


            var reportsRoot =
                Path.GetFullPath(
                    reportsFolder
                );


            var filePath =
                Path.GetFullPath(
                    report.FileUrl
                );


            var rootWithSeparator =
                reportsRoot.TrimEnd(
                    Path.DirectorySeparatorChar,
                    Path.AltDirectorySeparatorChar
                )
                + Path.DirectorySeparatorChar;


            // Prevent the Trainer Portal endpoint from
            // reading files outside its configured folder.
            if (
                !filePath.StartsWith(
                    rootWithSeparator,
                    StringComparison.OrdinalIgnoreCase
                )
            )
            {
                return null;
            }


            var fileName =
                Path.GetFileName(
                    filePath
                );


            // Only PDFs generated by the dedicated
            // Trainer Portal generator are accepted.
            if (
                !fileName.StartsWith(
                    "trainer-portal-report-",
                    StringComparison.OrdinalIgnoreCase
                )
            )
            {
                return null;
            }


            if (
                !string.Equals(
                    Path.GetExtension(fileName),
                    ".pdf",
                    StringComparison.OrdinalIgnoreCase
                )
            )
            {
                return null;
            }


            if (
                !File.Exists(
                    filePath
                )
            )
            {
                return null;
            }


            return filePath;
        }


        // ==========================================================
        // Analytics / Aggregation
        // ==========================================================

        public Task<DashboardChartsDTO>
            GetDashboardChartsAsync()
        {
            return _repository
                .GetDashboardChartsAsync();
        }


        public Task<BatchPerformanceReportDTO?>
            GetBatchPerformanceAsync(
                int batchId
            )
        {
            return _repository
                .GetBatchPerformanceAsync(
                    batchId
                );
        }

        public Task<BatchPerformanceReportDTO?> GetBatchPerformanceAsync(
           int batchId, int pageNumber, int pageSize)
          => _repository.GetBatchPerformanceAsync(batchId, pageNumber, pageSize);

        public Task<AttendanceReportDTO?>
            GetCompanyAttendanceReportAsync(
                int companyId
            )
        {
            return _repository
                .GetCompanyAttendanceReportAsync(
                    companyId
                );
        }


        public Task<List<ChartPointDTO>>
            GetCompanyAttendanceChartAsync(
                int companyId
            )
        {
            return _repository
                .GetCompanyAttendanceChartAsync(
                    companyId
                );
        }


        public Task<List<ChartPointDTO>>
            GetCompanyProgramDistributionAsync(
                int companyId
            )
        {
            return _repository
                .GetCompanyProgramDistributionAsync(
                    companyId
                );
        }


        public Task<List<int>>
            GetCompanyTopPerformerTraineeIdsAsync(
                int companyId,
                int take
            )
        {
            return _repository
                .GetCompanyTopPerformerTraineeIdsAsync(
                    companyId,
                    take
                );
        }


        public Task<List<int>>
            GetCompanyAtRiskTraineeIdsAsync(
                int companyId,
                int take
            )
        {
            return _repository
                .GetCompanyAtRiskTraineeIdsAsync(
                    companyId,
                    take
                );
        }


        public Task<TrainerKpisDTO>
            GetTrainerKpisAsync(
                int trainerId
            )
        {
            return _repository
                .GetTrainerKpisAsync(
                    trainerId
                );
        }
    }
}