// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Nafadh_Backend.DTOs;
using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;
using Nafadh_Backend.Repositories;

namespace Nafadh_Backend.Services
{
    public class SessionService : ISessionService
    {
        private readonly ISessionRepository _repository;
        private readonly ITrainerRepository _trainerRepository;
        private readonly IBatchRepository _batchRepository;

        public SessionService(
            ISessionRepository repository,
            ITrainerRepository trainerRepository,
            IBatchRepository batchRepository)
        {
            _repository = repository;
            _trainerRepository = trainerRepository;
            _batchRepository = batchRepository;
        }

        public async Task<List<SessionDto>> GetAllAsync(int? batchId, int? trainerId, DateTime? date)
        {
            var sessions = await _repository.GetAllAsync(batchId, trainerId, date);
            return sessions.Select(MapToDto).ToList();
        }

        public async Task<SessionDto?> GetByIdAsync(int id)
        {
            var session = await _repository.GetByIdAsync(id);
            return session == null ? null : MapToDto(session);
        }

        public async Task<SessionDto> CreateAsync(CreateSessionDto dto)
        {
            // 1. التحقق من وجود الدفعة
            var batchExists = await _batchRepository.GetByIdAsync(dto.BatchId) != null;
            if (!batchExists)
            {
                throw new InvalidOperationException($"Batch with ID {dto.BatchId} does not exist.");
            }

            // 2. التحقق من وجود المدرب (في حال كان المفهوم يتطلب وجود مدرب أكبر من 0)
            if (dto.TrainerId > 0)
            {
                var trainerExists = await _trainerRepository.GetByIdAsync(dto.TrainerId) != null;
                if (!trainerExists)
                {
                    throw new InvalidOperationException($"Trainer with ID {dto.TrainerId} does not exist.");
                }
            }

            // 3. إنشاء الجلسة
            var entity = new NFD_Session
            {
                BatchId = dto.BatchId,
                TrainerId = dto.TrainerId,
                SessionDate = dto.SessionDate,
                StartTime = dto.StartTime,
                EndTime = dto.EndTime,
                MeetingLink = dto.MeetingLink,
                Topic = dto.Topic,
                LearningObjectives = dto.LearningObjectives,
                Status = NFD_SessionStatus.Scheduled
            };

            var created = await _repository.AddAsync(entity);
            return MapToDto(created);
        }

        public async Task<bool> UpdateAsync(int id, UpdateSessionDto dto)
        {
            var session = await _repository.GetByIdAsync(id);
            if (session == null) return false;

            session.Topic = dto.Topic;
            session.MeetingLink = dto.MeetingLink;
            session.RecordingUrl = dto.RecordingUrl;
            session.LearningObjectives = dto.LearningObjectives;
            session.Summary = dto.Summary;

            await _repository.UpdateAsync(session);
            return true;
        }

        public async Task<bool> UpdateStatusAsync(int id, UpdateSessionStatusDto dto)
        {
            var session = await _repository.GetByIdAsync(id);
            if (session == null) return false;

            session.Status = dto.Status;
            await _repository.UpdateAsync(session);
            return true;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            var session = await _repository.GetByIdAsync(id);
            if (session == null) return false;

            await _repository.DeleteAsync(id);
            return true;
        }

        public async Task<List<SessionDto>> GetCalendarAsync(int batchId)
        {
            var sessions = await _repository.GetByBatchIdAsync(batchId);
            return sessions.Select(MapToDto).ToList();
        }

        private static SessionDto MapToDto(NFD_Session s) => new SessionDto
        {
            SessionId = s.SessionId,
            BatchId = s.BatchId,
            TrainerId = s.TrainerId,
            SessionDate = s.SessionDate,
            StartTime = s.StartTime,
            EndTime = s.EndTime,
            MeetingLink = s.MeetingLink,
            Topic = s.Topic,
            LearningObjectives = s.LearningObjectives,
            RecordingUrl = s.RecordingUrl,
            Summary = s.Summary,
            Status = s.Status
        };
    }
}