// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.Models;
using Nafadh_Backend.Repositories;
using Nafadh_Backend.DTOs;

namespace Nafadh_Backend.Services
{
    public class SupportTicketService : ISupportTicketService
    {
        private readonly ISupportTicketRepository _repository;

        public SupportTicketService(ISupportTicketRepository repository)
        {
            _repository = repository;
        }

       
        public async Task<SupportTicketDTO?> GetTicketByIdAsync(int id)
        {
            NFD_SupportTicket ticket = await _repository.GetByIdAsync(id);

            if (ticket == null)
            {
                return null;
            }

            SupportTicketDTO supportTicket = new SupportTicketDTO
            {
                TicketId = ticket.TicketId,
                Subject = ticket.Subject,
                Message = ticket.Message,
                Status = ticket.Status,
                CreatedAt = ticket.CreatedAt,
                UserId = ticket.UserId
            };
            return supportTicket;
        }

        public async Task<IEnumerable<SupportTicketDTO>> GetTicketsByUserIdAsync(int userId)
        {
            IEnumerable<NFD_SupportTicket> tickets = await _repository.GetUserTicketsAsync(userId);

            return tickets.Select(t => new SupportTicketDTO
            {
                TicketId = t.TicketId,
                Subject = t.Subject,
                Message = t.Message,
                Status = t.Status,
                CreatedAt = t.CreatedAt,
                UserId = t.UserId
            });
        }

    }
}