// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.DTOs;
using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;
using Nafadh_Backend.Repositories;

namespace Nafadh_Backend.Services
{
    public class TrackService : ITrackService
    {
        private readonly ITrackRepository _repository;

        public TrackService(ITrackRepository repository)
        {
            _repository = repository;
        }

        //List all tracks
        public async Task<IEnumerable<TrackDto>> GetAllTracksAsync()
        {
            var tracks = await _repository.GetAllAsync();
            return tracks.Select(MapToDto);
        }

        // Get track details
        public async Task<TrackDto?> GetTrackByIdAsync(int id)
        {
            var track = await _repository.GetByIdAsync(id);
            return track is null ? null : MapToDto(track);
        }

        // Create a new track
        public async Task<TrackDto> CreateTrackAsync(CreateTrackDto dto)
        {
            var track = new NFD_Track
            {
                Name = dto.Name,
                Description = dto.Description,
                Status = NFD_TrackStatus.Active
            };

            var created = await _repository.AddAsync(track);
            return MapToDto(created);
        }

        //Update track name/description/status
        public async Task<TrackDto> UpdateTrackAsync(int id, UpdateTrackDto dto)
        {
            var track = await _repository.GetByIdAsync(id);
            if (track is null) return null;

            track.Name = dto.Name;
            track.Description = dto.Description;
            track.Status = dto.Status;

            await _repository.UpdateAsync(track);
            return MapToDto(track);
        }

        //Archive/remove a track
        public async Task<bool> DeleteTrackAsync(int id)
        {
            var track = await _repository.GetByIdAsync(id);
            if (track is null) return false;

            await _repository.DeleteAsync(track);
            return true;
        }


    }
}