// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.DTOs;
using Nafadh_Backend.Models;
using Nafadh_Backend.Repositories;

namespace Nafadh_Backend.Services
{
    public class TrainingMaterialService : ITrainingMaterialService
    {
        private readonly ITrainingMaterialRepository _repository;

        public TrainingMaterialService(ITrainingMaterialRepository repository)
        {
            _repository = repository;
        }


        // Get all materials attached to a specific lesson.
        // Endpoint:
        // GET /api/TrainingMaterial/lesson/{lessonId}
        public async Task<IEnumerable<TrainingMaterialDto>> GetByLessonIdAsync(int lessonId)
        {
            // TODO:
            // Validate that Lesson exists.
            // Lesson belongs to Lesson module owned by another developer.


            var materials = await _repository.GetByLessonIdAsync(lessonId);


            // Convert Model objects into DTO objects before returning.
            return materials.Select(m => new TrainingMaterialDto
            {
                MaterialId = m.MaterialId,

                FileUrl = m.FileUrl,

                FileType = m.FileType,

                UploadDate = m.UploadDate,

                LessonId = m.LessonId,

                UploadedByUserId = m.UploadedByUserId
            });
        }




        // Create new training material.
        // Endpoint:
        // POST /api/TrainingMaterial
        public async Task<TrainingMaterialDto> CreateAsync(
            CreateTrainingMaterialDto dto,
            int userId)
        {

            // Validate FileType before saving.
            if (dto.FileType == null)
            {
                throw new ArgumentException("File type is required.");
            }


            // TODO:
            // Validate that LessonId exists.
            // Lesson entity belongs to another developer.


            // Create database model.
            var material = new NFD_TrainingMaterial
            {
                FileUrl = dto.FileUrl,


                // Convert nullable enum value to normal enum.
                FileType = dto.FileType.Value,


                LessonId = dto.LessonId,


                // UserId comes from JWT Token.
                // We do not trust UserId from client request.
                UploadedByUserId = userId,


                // Set upload date automatically.
                UploadDate = DateTime.UtcNow
            };



            // Save data through repository.
            var createdMaterial =
                await _repository.CreateAsync(material);



            // Return DTO response.
            return new TrainingMaterialDto
            {
                MaterialId = createdMaterial.MaterialId,

                FileUrl = createdMaterial.FileUrl,

                FileType = createdMaterial.FileType,

                UploadDate = createdMaterial.UploadDate,

                LessonId = createdMaterial.LessonId,

                UploadedByUserId = createdMaterial.UploadedByUserId
            };
        }





        // Update existing training material.
        // Endpoint:
        // PUT /api/TrainingMaterial/{id}
        public async Task<bool> UpdateAsync(
            int id,
            UpdateTrainingMaterialDto dto)
        {

            // Find material by ID.
            var material =
                await _repository.GetByIdAsync(id);



            // If material does not exist.
            if (material == null)
            {
                return false;
            }



            // Validate FileType.
            if (dto.FileType == null)
            {
                return false;
            }



            // Update allowed fields only.
            material.FileUrl = dto.FileUrl;

            material.FileType = dto.FileType.Value;



            // Save changes.
            await _repository.UpdateAsync(material);



            return true;
        }





        // Delete training material.
        // Endpoint:
        // DELETE /api/TrainingMaterial/{id}
        public async Task<bool> DeleteAsync(int id)
        {

            // Get material from database.
            var material =
                await _repository.GetByIdAsync(id);



            // Material not found.
            if (material == null)
            {
                return false;
            }



            // Delete record.
            await _repository.DeleteAsync(material);



            return true;
        }





        // Get file URL for download or streaming.
        // Endpoint:
        // GET /api/TrainingMaterial/{id}/download
        public async Task<string?> GetDownloadUrlAsync(int id)
        {

            // Find material.
            var material =
                await _repository.GetByIdAsync(id);



            // Return null if not found.
            if (material == null)
            {
                return null;
            }



            // Return file location.
            return material.FileUrl;
        }
    }
}