#nullable enable

// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.DTOs;
using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;
using Nafadh_Backend.Repositories;

namespace Nafadh_Backend.Services
{
    public class WarningService : IWarningService
    {
        private readonly IWarningRepository _warningRepository;

        public WarningService(IWarningRepository repository)
        {
            _warningRepository = repository;
        }

        // Get warnings by enrollment
        // GET /api/Warning/enrollment/{enrollmentId}
        public async Task<IEnumerable<WarningOutputDTO>> GetWarningsByEnrollmentAsync(
            int enrollmentId)
        {
            var warnings = await _warningRepository
                .GetWarningsByEnrollmentAsync(enrollmentId);

            return warnings.Select(MapToDTO);
        }

        // Get warning details by ID
        // GET /api/Warning/{id}
        public async Task<WarningDetailsDTO?> GetWarningByIdAsync(
            int id)
        {
            var warning = await _warningRepository
                .GetWarningByIdAsync(id);

            return warning == null
                ? null
                : MapToDetailsDTO(warning);
        }

        // Create warning
        // POST /api/Warning
        public async Task CreateWarningAsync(
            WarningInputDTO dto)
        {
            var warning = new NFD_Warning
            {
                EnrollmentId = dto.EnrollmentId,
                Type = dto.Type,
                Level = dto.Level,
                Evidence = dto.Evidence,

                // Temporary value for testing.
                // Later this should come from the logged-in user.
                RaisedByUserId = 8,

                Status = NFD_WarningStatus.Open,
                IssuedDate = DateTime.UtcNow
            };

            await _warningRepository.AddWarningAsync(warning);
        }

        // Update warning status
        // PUT /api/Warning/{id}/status
        public async Task UpdateWarningStatusAsync(
            int id,
            WarningStatusInputDTO dto)
        {
            await _warningRepository
                .UpdateWarningStatusAsync(id, dto.Status);
        }

        // Resolve warning
        // PUT /api/Warning/{id}/resolve
        public async Task ResolveWarningAsync(
            int id,
            WarningResolveInputDTO dto)
        {
            await _warningRepository
                .ResolveWarningAsync(id, dto.Resolution);
        }

        // Get pending warnings
        // GET /api/Warning/pending
        public async Task<IEnumerable<WarningOutputDTO>> GetPendingWarningsAsync()
        {
            var warnings = await _warningRepository
                .GetPendingWarningsAsync();

            return warnings.Select(MapToDTO);
        }

        // Get warnings by level
        // GET /api/Warning/level/{level}
        public async Task<IEnumerable<WarningOutputDTO>> GetWarningsByLevelAsync(
            NFD_WarningLevel level)
        {
            var warnings = await _warningRepository
                .GetWarningsByLevelAsync(level);

            return warnings.Select(MapToDTO);
        }

        // Convert Entity to Output DTO
        private WarningOutputDTO MapToDTO(
            NFD_Warning warning)
        {
            return new WarningOutputDTO
            {
                WarningId = warning.WarningId,
                EnrollmentId = warning.EnrollmentId,
                Type = warning.Type,
                Level = warning.Level,
                Evidence = warning.Evidence,
                Status = warning.Status,
                Resolution = warning.Resolution,
                IssuedDate = warning.IssuedDate
            };
        }

        // Convert Entity to Details DTO
        private WarningDetailsDTO MapToDetailsDTO(
            NFD_Warning warning)
        {
            return new WarningDetailsDTO
            {
                WarningId = warning.WarningId,
                EnrollmentId = warning.EnrollmentId,
                Type = warning.Type,
                Level = warning.Level,
                Evidence = warning.Evidence,
                Status = warning.Status,
                Resolution = warning.Resolution,
                IssuedDate = warning.IssuedDate
            };
        }
    }
}