// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Nafadh_Backend.Enums;

namespace Nafadh_Backend.Models
{
    /// <summary>
    /// Maps to the [NFD_SessionAttendances] table.
    /// </summary>
    public class NFD_SessionAttendance
    {
        [Key]
        public int AttendanceId { get; set; }

        public NFD_AttendanceStatus Status { get; set; }
        [MaxLength(300)]
        public string? Note { get; set; }

        public int SessionId { get; set; }
        public NFD_Session Session { get; set; } = null!;

        public int TraineeId { get; set; }
        public NFD_Trainee Trainee { get; set; } = null!;

    }
}