// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Nafadh_Backend.Enums;

namespace Nafadh_Backend.Models
{
    /// <summary>
    /// Maps to the [NFD_Rubrics] table.
    /// </summary>
    public class NFD_Rubric
    {
        [Key]
        public int RubricId { get; set; }

        [Required]
        [MaxLength(150)]
        public string Criterion { get; set; } = string.Empty;
        [Column(TypeName = "decimal(18,2)")]
        public decimal Weight { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal MaxScore { get; set; }

        public int TaskId { get; set; }
        public NFD_Task Task { get; set; } = null!;

    }
}