// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Nafadh_Backend.Enums;

namespace Nafadh_Backend.Models
{
    /// <summary>
    /// Maps to the [NFD_SystemSettings] table.
    /// </summary>
    public class NFD_SystemSetting
    {
        [Key]
        public int SettingId { get; set; }

        [Required]
        [MaxLength(100)]
        public string Key { get; set; } = string.Empty;
        [Required]
        public string Value { get; set; } = string.Empty;
        [MaxLength(300)]
        public string? Description { get; set; }

    }
}