// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Nafadh_Backend.Enums;

namespace Nafadh_Backend.Models
{
    /// <summary>
    /// Maps to the [NFD_Trainees] table.
    /// </summary>
    public class NFD_Trainee
    {
        [Key]
        public int TraineeId { get; set; }

        public int NationalId { get; set; }
        [MaxLength(150)]
        public string? University { get; set; }
        [MaxLength(100)]
        public string? Major { get; set; }
        [MaxLength(50)]
        public string? AcademicLevel { get; set; }
        public string? Skills { get; set; }
        [MaxLength(300)]
        public string? ResumeUrl { get; set; }
        [MaxLength(300)]
        public string? GitHubUrl { get; set; }
        [MaxLength(300)]
        public string? LinkedInUrl { get; set; }
        public NFD_TraineeStatus Status { get; set; }
        public NFD_VerificationStatus VerificationStatus { get; set; }

        public int UserId { get; set; }
        public NFD_User User { get; set; } = null!;

        public int? CompanyId { get; set; }
        public NFD_Company? Company { get; set; }

        public ICollection<NFD_Enrollment> Enrollments { get; set; } = new List<NFD_Enrollment>();
        public ICollection<NFD_TraineeModuleProgress> TraineeModuleProgresses { get; set; } = new List<NFD_TraineeModuleProgress>();
        public ICollection<NFD_SessionAttendance> SessionAttendances { get; set; } = new List<NFD_SessionAttendance>();
        public ICollection<NFD_Submission> Submissions { get; set; } = new List<NFD_Submission>();
        public ICollection<NFD_ProjectMember> ProjectMembers { get; set; } = new List<NFD_ProjectMember>();
        // NEW: feedback submitted by this trainee, and badges earned by this trainee.
        public ICollection<NFD_Feedback> Feedbacks { get; set; } = new List<NFD_Feedback>();
        public ICollection<NFD_TraineeBadge> TraineeBadges { get; set; } = new List<NFD_TraineeBadge>();

    }
}