// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Nafadh_Backend.Enums;

namespace Nafadh_Backend.Models
{
    /// <summary>
    /// Maps to the [NFD_Certificates] table.
    /// </summary>
    public class NFD_Certificate
    {
        [Key]
        public int CertificateId { get; set; }

        public NFD_CertificateType Type { get; set; }
        public DateTime IssueDate { get; set; }
        [MaxLength(300)]
        public string? FileUrl { get; set; }

        public int EnrollmentId { get; set; }
        public NFD_Enrollment Enrollment { get; set; } = null!;

    }
}