// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Nafadh_Backend.Enums;

namespace Nafadh_Backend.Models
{
    /// <summary>
    /// Maps to the [NFD_Tracks] table.
    /// </summary>
    public class NFD_Track
    {
        [Key]
        public int TrackId { get; set; }

        [Required]
        [MaxLength(150)]
        public string Name { get; set; } = string.Empty;
        public string? Description { get; set; }
        public NFD_TrackStatus Status { get; set; }

        public ICollection<NFD_Program> Programs { get; set; } = new List<NFD_Program>();

    }
}