// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Nafadh_Backend.Enums;

namespace Nafadh_Backend.Models
{
    /// <summary>
    /// Maps to the [NFD_Excuses] table.
    /// </summary>
    public class NFD_Excuse
    {
        [Key]
        public int ExcuseId { get; set; }

        [Required]
        [MaxLength(300)]
        public string Reason { get; set; } = string.Empty;
        [MaxLength(300)]
        public string? ProofUrl { get; set; }
        public NFD_ExcuseStatus Status { get; set; }

        public int DailyAttendanceId { get; set; }
        public NFD_DailyAttendance DailyAttendance { get; set; } = null!;

        public int? ReviewedByUserId { get; set; }
        public NFD_User? User { get; set; }

    }
}