// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Nafadh_Backend.Enums;

namespace Nafadh_Backend.Models
{
    /// <summary>
    /// Maps to the [NFD_Warnings] table.
    /// </summary>
    public class NFD_Warning
    {
        [Key]
        public int WarningId { get; set; }

        public NFD_WarningType Type { get; set; }
        public NFD_WarningLevel Level { get; set; }
        public string? Evidence { get; set; }
        public NFD_WarningStatus Status { get; set; }
        public string? Resolution { get; set; }
        public DateTime IssuedDate { get; set; }

        public int EnrollmentId { get; set; }
        public NFD_Enrollment Enrollment { get; set; } = null!;

        public int RaisedByUserId { get; set; }
        public NFD_User User { get; set; } = null!;

    }
}