// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Nafadh_Backend.Enums;

namespace Nafadh_Backend.Models
{
    /// <summary>
    /// Maps to the [NFD_EvaluationCriteria] table.
    /// </summary>
    public class NFD_EvaluationCriterion
    {
        [Key]
        public int CriteriaId { get; set; }

        [Required]
        [MaxLength(150)]
        public string Name { get; set; } = string.Empty;
        [Column(TypeName = "decimal(18,2)")]
        public decimal Weight { get; set; }
        // NEW: point-sum-to-total support, alongside Weight (both fields required
        // per finalized decision — exact rollup formula chosen at scoring time).
        [Column(TypeName = "decimal(18,2)")]
        public decimal MaxPoints { get; set; }

        public int TemplateId { get; set; }
        public NFD_EvaluationTemplate EvaluationTemplate { get; set; } = null!;
        // NEW: per-criterion scores recorded against this criterion (see NFD_EvaluationCriterionScore).
        public ICollection<NFD_EvaluationCriterionScore> CriterionScores { get; set; } = new List<NFD_EvaluationCriterionScore>();

    }
}