// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Nafadh_Backend.Enums;

namespace Nafadh_Backend.Models
{
    /// <summary>
    /// Maps to the [NFD_Modules] table.
    /// </summary>
    public class NFD_Module
    {
        [Key]
        public int ModuleId { get; set; }

        [Required]
        [MaxLength(150)]
        public string Title { get; set; } = string.Empty;
        [Column(TypeName = "decimal(18,2)")]
        public decimal OrderIndex { get; set; }
        public DateTime? AvailableFrom { get; set; }
        public DateTime? AvailableTo { get; set; }
        public bool IsArchived { get; set; }

        public int ProgramId { get; set; }
        public NFD_Program Program { get; set; } = null!;

        public int? PrerequisiteModuleId { get; set; }
        public NFD_Module? PrerequisiteModule { get; set; }

        public ICollection<NFD_Lesson> Lessons { get; set; } = new List<NFD_Lesson>();
        public ICollection<NFD_TraineeModuleProgress> TraineeModuleProgresses { get; set; } = new List<NFD_TraineeModuleProgress>();

    }
}