// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Nafadh_Backend.Enums;

namespace Nafadh_Backend.Models
{
    /// <summary>
    /// Maps to the [NFD_CompanyPayments] table.
    /// </summary>
    public class NFD_CompanyPayment
    {
        [Key]
        public int CompanyPaymentId { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal TotalAmount { get; set; }
        public NFD_PaymentStatus Status { get; set; }

        public int CompanyId { get; set; }
        public NFD_Company Company { get; set; } = null!;

        public int BatchId { get; set; }
        public NFD_Batch Batch { get; set; } = null!;

        public ICollection<NFD_CompanyPaymentSchedule> CompanyPaymentSchedules { get; set; } = new List<NFD_CompanyPaymentSchedule>();

    }
}