// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Nafadh_Backend.Enums;

namespace Nafadh_Backend.Models
{
    /// <summary>
    /// Maps to the [NFD_CompanyPrograms] table.
    /// </summary>
    public class NFD_CompanyProgram
    {
        public int CompanyId { get; set; }
        public int ProgramId { get; set; }

        public NFD_Company Company { get; set; } = null!;

        public NFD_Program Program { get; set; } = null!;

    }
}