// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Nafadh_Backend.Enums;

namespace Nafadh_Backend.Models
{
    /// <summary>
    /// Maps to the [NFD_Messages] table.
    /// </summary>
    public class NFD_Message
    {
        [Key]
        public int MessageId { get; set; }

        [Required]
        public string Content { get; set; } = string.Empty;
        public DateTime SentDate { get; set; }
        public NFD_MessageStatus Status { get; set; }

        public int SenderId { get; set; }
        public NFD_User Sender { get; set; } = null!;

        public int ReceiverId { get; set; }
        public NFD_User Receiver { get; set; } = null!;

    }
}