// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Nafadh_Backend.Enums;

namespace Nafadh_Backend.Models
{
    /// <summary>
    /// Maps to the [NFD_Programs] table.
    /// </summary>
    public class NFD_Program
    {
        [Key]
        public int ProgramId { get; set; }

        [Required]
        [MaxLength(150)]
        public string Title { get; set; } = string.Empty;
        public string? Description { get; set; }
        [MaxLength(100)]
        public string? Category { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal DurationHours { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal Price { get; set; }
        public NFD_ProgramStatus Status { get; set; }

        public int TrackId { get; set; }
        public NFD_Track Track { get; set; } = null!;

        public ICollection<NFD_Batch> Batches { get; set; } = new List<NFD_Batch>();
        public ICollection<NFD_Module> Modules { get; set; } = new List<NFD_Module>();
        public ICollection<NFD_Project> Projects { get; set; } = new List<NFD_Project>();
        public ICollection<NFD_CompanyProgram> CompanyPrograms { get; set; } = new List<NFD_CompanyProgram>();

    }
}