// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using Nafadh_Backend.Services;

namespace Nafadh_Backend.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class CertificateController : ControllerBase
    {
        private readonly ICertificateService _service;

        public CertificateController(ICertificateService service)
        {
            _service = service;
        }

        // TODO: implement endpoints for this entity
        // GET certificate by enrollment
        [HttpGet("enrollment/{enrollmentId}")]
        public async Task<IActionResult> GetCertificateByEnrollment(int enrollmentId)
        {

            var result =
                await _service.GetCertificateByEnrollmentIdAsync(enrollmentId);


            if (result == null)
                return NotFound();


            return Ok(result);
        }

    }
}