// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using Nafadh_Backend.Services;
using Nafadh_Backend.DTOs;

namespace Nafadh_Backend.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class CertificateController : ControllerBase
    {
        private readonly ICertificateService _service;

        public CertificateController(ICertificateService service)
        {
            _service = service;
        }

        // TODO: implement endpoints for this entity

        // GET certificate by enrollment
        [HttpGet("enrollment/{enrollmentId}")]
        public async Task<IActionResult> GetCertificateByEnrollment(int enrollmentId)
        {

            var result =
                await _service.GetCertificateByEnrollmentIdAsync(enrollmentId);


            if (result == null)
                return NotFound();


            return Ok(result);
        }
        // Create certificate
        [HttpPost]
        public async Task<IActionResult> AddCertificate(CertificateInputDTO dto)
        {

            var result = await _service.AddCertificateAsync(dto);
            if (result == null)
            {
                return BadRequest("Unable to issue certificate.");
            }

            return Ok(new
            {
                Message = "Certificate issued successfully",
                Certificate = result
            });
        }

        // GET Certificate/{id}/download
        [HttpGet("{id}/download")]
        public async Task<IActionResult> DownloadCertificate(int id)
        {
            var fileUrl = await _service.DownloadCertificateAsync(id);

            if (fileUrl == null)
                return NotFound();

            var filePath = Path.Combine(
                Directory.GetCurrentDirectory(),
                "wwwroot",
                fileUrl
            );

            if (!System.IO.File.Exists(filePath))
                return NotFound("Certificate file not found.");

            var fileBytes = await System.IO.File.ReadAllBytesAsync(filePath);

            var fileName = Path.GetFileName(filePath);

            return File(
                fileBytes,
                "application/pdf",
                fileName
            );
        }

        // Get all certificates for trainee
        [HttpGet("trainee/{traineeId}")]
        public async Task<IActionResult> GetCertificatesByTrainee(int traineeId)
        {

            var result =await _service.GetCertificatesByTraineeIdAsync(traineeId);

            if (result == null || !result.Any())
                return NotFound();

            return Ok(result);
        }



    }
}