// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using Nafadh_Backend.DTOs;
using Nafadh_Backend.Enums;
using Nafadh_Backend.Services;
using static Nafadh_Backend.DTOs.EnrollmentDTO;

namespace Nafadh_Backend.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class EnrollmentController : ControllerBase
    {
        private readonly IEnrollmentService _service;

        public EnrollmentController(IEnrollmentService service)
        {
            _service = service;
        }

        // GET /api/Enrollment?batchId=&traineeId=&companyId=&status=  (filters all optional)
        [HttpGet]
        public async Task<ActionResult<IEnumerable<EnrollmentDTO>>> GetAll(
            [FromQuery] int? batchId,
            [FromQuery] int? traineeId,
            [FromQuery] int? companyId,
            [FromQuery] NFD_EnrollmentCompletionStatus? status)
        {
            var filter = new EnrollmentFilterDto
            {
                BatchId = batchId,
                TraineeId = traineeId,
                CompanyId = companyId,
                Status = status
            };
            var enrollments = await _service.GetAllEnrollmentsAsync(filter);
            return Ok(enrollments);
        }
    }
}