// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using Nafadh_Backend.DTOs;
using Nafadh_Backend.Enums;
using Nafadh_Backend.Services;

namespace Nafadh_Backend.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class ProgramController : ControllerBase
    {
        private readonly IProgramService _service;

        public ProgramController(IProgramService service)
        {
            _service = service;
        }

        // GET /api/Program?trackId=&status=&category=  (filters all optional)
        [HttpGet]
        public async Task<ActionResult<IEnumerable<ProgramDto>>> GetAll(
            [FromQuery] int? trackId,
            [FromQuery] NFD_ProgramStatus? status,
            [FromQuery] string? category)
        {
            var filter = new ProgramFilterDto { TrackId = trackId, Status = status, Category = category };
            var programs = await _service.GetAllProgramsAsync(filter);
            return Ok(programs);
        }

        // GET /api/Program/{id}
        [HttpGet("{id:int}")]
        public async Task<ActionResult<ProgramDto>> GetById(int id)
        {
            var program = await _service.GetProgramByIdAsync(id);
            if (program is null)
                return NotFound(new { message = $"Program with ID {id} was not found." });

            return Ok(program);
        }
    }
}