// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using Nafadh_Backend.Services;

namespace Nafadh_Backend.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class RubricController : ControllerBase
    {
        private readonly IRubricService _service;

        public RubricController(IRubricService service)
        {
            _service = service;
        }

        // TODO: implement endpoints for this entity
    }
}