// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using Nafadh_Backend.DTOs;
using Nafadh_Backend.Services;

namespace Nafadh_Backend.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class SystemSettingController : ControllerBase
    {
        private readonly ISystemSettingService _service;

        public SystemSettingController(ISystemSettingService service)
        {
            _service = service;
        }

        [HttpGet]
        public async Task<IActionResult> GetAllSystemSettings()
        {
            var settings = await _service.GetAllSystemSettingsAsync();

            return Ok(settings);
        }


        [HttpGet("{key}")]
        public async Task<IActionResult> GetSystemSettingByKey(string key)
        {
            var setting = await _service.GetSystemSettingByKeyAsync(key);

            if (setting == null)
                return NotFound();

            return Ok(setting);
        }


        [HttpPost]
        public async Task<IActionResult> AddSystemSetting(SystemSettingInputDTO input)
        {
            await _service.AddSystemSettingAsync(input);

            return Ok("System Setting added successfully");
        }


        [HttpPut("{key}")]
        public async Task<IActionResult> UpdateSystemSetting(string key, UpdateSystemSettingDTO input)
        {
            var result = await _service.UpdateSystemSettingAsync(key, input);

            if (!result)
                return NotFound();

            return Ok("System Setting updated successfully");
        }


        [HttpDelete("{key}")]
        public async Task<IActionResult> DeleteSystemSetting(string key)
        {
            var result = await _service.DeleteSystemSettingAsync(key);

            if (!result)
                return NotFound();

            return Ok("System Setting deleted successfully");
        }
    }
}