// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using Nafadh_Backend.DTOs;
using Nafadh_Backend.Services;

namespace Nafadh_Backend.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class TrackController : ControllerBase
    {
        private readonly ITrackService _service;

        public TrackController(ITrackService service)
        {
            _service = service;
        }

        // GET /api/Track
        [HttpGet]
        public async Task<ActionResult<IEnumerable<TrackDto>>> GetAll()
        {
            var tracks = await _service.GetAllTracksAsync();
            return Ok(tracks);
        }
     
        // GET /api/Track/{id}
        [HttpGet("{id:int}")]
        public async Task<ActionResult<TrackDto>> GetById(int id)
        {
            var track = await _service.GetTrackByIdAsync(id);
            if (track is null)
                return NotFound(new { message = $"Track with ID {id} was not found." });

            return Ok(track);
        }
    }
}