// <auto-generated>
// Added as part of Nafadh backend upgrade (Phase 2 - Contract Alignment).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using Nafadh_Backend.Services;

namespace Nafadh_Backend.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class TraineeBadgeController : ControllerBase
    {
        private readonly IBadgeService _service;

        public TraineeBadgeController(IBadgeService service)
        {
            _service = service;
        }

        // GET: api/TraineeBadge/trainee/{traineeId}
        [HttpGet("trainee/{traineeId}")]
        public async Task<IActionResult> GetByTrainee(int traineeId)
        {
            var earned = await _service.GetTraineeBadgesAsync(traineeId);
            return Ok(earned);
        }
    }
}
