// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using Nafadh_Backend.Services;
using Nafadh_Backend.DTOs;

using System.Threading.Tasks;

namespace Nafadh_Backend.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class TrainerController : ControllerBase
    {
        private readonly ITrainerService _service;

        public TrainerController(ITrainerService service)
        {
            _service = service;
        }

        [HttpGet]
        public async Task<IActionResult> GetAll([FromQuery] TrainerFilterDto filter)
        {
            var (items, total) = await _service.GetAllAsync(filter);
            return Ok(new { Items = items, TotalCount = total });
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(int id)
        {
            var profile = await _service.GetByIdAsync(id);
            if (profile == null) return NotFound();
            return Ok(profile);
        }

        // Retrieves the trainer profile linked to the specified user account.
        [HttpGet("by-user/{userId}")]
        public async Task<IActionResult> GetByUserId(int userId)
        {
            var profile = await _service.GetByUserIdAsync(userId);

            if (profile == null)
                return NotFound();

            return Ok(profile);
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromBody] TrainerCreateDto dto)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            var created = await _service.CreateAsync(dto);
            if (created == null) return Conflict(new { Message = "Trainer profile for this user already exists or could not be created." });

            return CreatedAtAction(nameof(GetById), new { id = created.TrainerId }, created);
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(int id, [FromBody] TrainerUpdateDto dto)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            var ok = await _service.UpdateAsync(id, dto);
            if (!ok) return NotFound();
            return NoContent();
        }
        // =====================================================
        // UPLOAD TRAINER PROFILE IMAGE
        // =====================================================

        [HttpPost("{id}/profile-image")]
        [Consumes("multipart/form-data")]
        [RequestSizeLimit(6 * 1024 * 1024)]
        public async Task<IActionResult> UploadProfileImage(
            int id,
            [FromForm] IFormFile file
        )
        {
            try
            {
                var profileImageUrl =
                    await _service.UploadProfileImageAsync(
                        id,
                        file
                    );


                // Trainer does not exist.
                if (profileImageUrl == null)
                {
                    return NotFound(
                        new
                        {
                            message = "Trainer not found."
                        }
                    );
                }


                // Return the public image URL
                // to the frontend.
                return Ok(
                    new
                    {
                        profileImageUrl
                    }
                );
            }
            catch (ArgumentException ex)
            {
                // Invalid image type, extension,
                // empty file, or file too large.
                return BadRequest(
                    new
                    {
                        message = ex.Message
                    }
                );
            }
            catch (InvalidOperationException ex)
            {
                // Storage or database operation failed.
                return StatusCode(
                    StatusCodes.Status500InternalServerError,
                    new
                    {
                        message = ex.Message
                    }
                );
            }
        }

        [HttpPut("{id}/status")]
        public async Task<IActionResult> UpdateStatus(int id, [FromBody] TrainerStatusUpdateDto dto)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            var ok = await _service.UpdateStatusAsync(id, dto);
            if (!ok) return NotFound();
            return NoContent();
        }

        [HttpGet("{id}/batches")]
        public async Task<IActionResult> GetBatches(int id)
        {
            var items = await _service.GetBatchesAsync(id);
            return Ok(items);
        }

        [HttpGet("{id}/evaluations")]
        public async Task<IActionResult> GetEvaluations(int id)
        {
            var items = await _service.GetEvaluationsAsync(id);
            return Ok(items);
        }
    }
}