// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Nafadh_Backend.DTOs;
using Nafadh_Backend.Services;
using System.Security.Claims;

namespace Nafadh_Backend.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    [Authorize]
    public class TraineeModuleProgressController : ControllerBase
    {
        private readonly ITraineeModuleProgressService _service;

        public TraineeModuleProgressController(ITraineeModuleProgressService service)
        {
            _service = service;
        }

        // -------------------------------------------------------
        // GET: /api/TraineeModuleProgress/trainee/{traineeId}
        // Returns all progress records for a trainee.
        // -------------------------------------------------------
        [HttpGet("trainee/{traineeId}")]
        public async Task<IActionResult> GetByTraineeId(int traineeId)
        {
            var result = await _service.GetByTraineeIdAsync(traineeId);
            return Ok(result);
        }

        // -------------------------------------------------------
        // POST: /api/TraineeModuleProgress/complete
        // Trainee marks a module as completed.
        // -------------------------------------------------------
        [HttpPost("complete")]
        [Authorize(Roles = "Trainee,CompanySupervisor,Admin")]
        public async Task<IActionResult> CompleteModule(CompleteModuleDto dto)
        {
            var traineeIdClaim = User.FindFirst(ClaimTypes.NameIdentifier) ?? User.FindFirst("sub");

            if (traineeIdClaim == null || string.IsNullOrEmpty(traineeIdClaim.Value))
            {
                return Unauthorized("Trainee ID not found in token.");
            }

            if (!int.TryParse(traineeIdClaim.Value, out int traineeId))
            {
                return BadRequest("Invalid Trainee ID format in token.");
            }

            try
            {
                var result = await _service.CompleteModuleAsync(dto, traineeId);
                return Ok(result);
            }
            catch (KeyNotFoundException ex)
            {
                return NotFound(ex.Message);
            }
        }

        // -------------------------------------------------------
        // PUT: /api/TraineeModuleProgress/{id}
        // Updates progress status (Trainer / Admin).
        // -------------------------------------------------------
        [HttpPut("{id}")]
        [Authorize(Roles = "Trainer,Admin,CompanySupervisor")]
        public async Task<IActionResult> Update(int id, UpdateTraineeModuleProgressDto dto)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var updated = await _service.UpdateAsync(id, dto);

            if (!updated)
            {
                return NotFound("Progress record not found.");
            }

            return NoContent();
        }

        // -------------------------------------------------------
        // GET: /api/TraineeModuleProgress/trainee/{traineeId}/percentage
        // Returns trainee overall completion percentage.
        // -------------------------------------------------------
        [HttpGet("trainee/{traineeId}/percentage")]
        public async Task<IActionResult> GetPercentage(int traineeId)
        {
            var result = await _service.GetProgressPercentageAsync(traineeId);
            return Ok(result);
        }

        // -------------------------------------------------------
        // GET: /api/TraineeModuleProgress/module/{moduleId}
        // Returns completion status of all trainees inside a specific module.
        // -------------------------------------------------------
        [HttpGet("module/{moduleId}")]
        public async Task<IActionResult> GetByModuleId(int moduleId)
        {
            try
            {
                var result = await _service.GetByModuleIdAsync(moduleId);
                return Ok(result);
            }
            catch (KeyNotFoundException ex)
            {
                return NotFound(ex.Message);
            }
        }
    }
}