// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using Nafadh_Backend.DTOs;
using Nafadh_Backend.Services;

namespace Nafadh_Backend.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class TrainingMaterialController : ControllerBase
    {
        private readonly ITrainingMaterialService _service;
        private readonly IConfiguration _configuration;


        // =====================================================
        // CONSTRUCTOR
        // =====================================================

        public TrainingMaterialController(
            ITrainingMaterialService service,
             IConfiguration configuration)
        {
            _service = service;
            _configuration = configuration;
        }


        // =====================================================
        // GET MATERIALS BY LESSON
        // GET: api/TrainingMaterial/lesson/{lessonId}
        // =====================================================

        [HttpGet("lesson/{lessonId}")]
        public async Task<IActionResult> GetByLesson(
            int lessonId)
        {
            var materials =
                await _service.GetByLessonIdAsync(
                    lessonId
                );

            return Ok(materials);
        }


        // =====================================================
        // CREATE TRAINING MATERIAL
        // POST: api/TrainingMaterial
        // Used for URLs / references / already uploaded files
        // =====================================================

        [HttpPost]
        public async Task<IActionResult> Create(
            CreateTrainingMaterialDto dto)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }


            var result =
                await _service.CreateAsync(
                    dto,
                    dto.UploadedByUserId
                );


            return CreatedAtAction(
                nameof(GetDownloadUrl),
                new
                {
                    id = result.MaterialId
                },
                result
            );
        }


        // =====================================================
        // UPLOAD FILE
        // POST: api/TrainingMaterial/upload
        // =====================================================

        [HttpPost("upload")]
        public async Task<IActionResult> Upload(
            [FromForm] UploadTrainingMaterialDto dto)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }


            // ---------------------------------------------
            // Validate file
            // ---------------------------------------------

            if (
                dto.File == null ||
                dto.File.Length == 0
            )
            {
                return BadRequest(
                    new
                    {
                        message =
                            "File is required."
                    }
                );
            }


        

            // ---------------------------------------------
            // Get upload folder from appsettings
            // Files are stored outside the project folder
            // so they are not committed to Git.
            // ---------------------------------------------

            var uploadsFolder =
                _configuration[
                    "Storage:TrainingMaterialsPath"
                ];


            if (string.IsNullOrWhiteSpace(uploadsFolder))
            {
                return StatusCode(
                    StatusCodes.Status500InternalServerError,
                    "Training materials storage path is not configured."
                );
            }


            // Create the external folder if it does not exist
            Directory.CreateDirectory(
                uploadsFolder
            );

            // ---------------------------------------------
            // Generate unique file name
            // ---------------------------------------------

            var extension =
                Path.GetExtension(
                    dto.File.FileName
                );


            var fileName =
                $"{Guid.NewGuid()}{extension}";


            var fullPath =
                Path.Combine(
                    uploadsFolder,
                    fileName
                );


            // ---------------------------------------------
            // Save physical file
            // ---------------------------------------------

            await using (
                var stream =
                    new FileStream(
                        fullPath,
                        FileMode.Create
                    )
            )
            {
                await dto.File.CopyToAsync(
                    stream
                );
            }


            // ---------------------------------------------
            // ---------------------------------------------
            // File URL saved in database
            // Request path comes from appsettings
            // ---------------------------------------------

            var requestPath = _configuration["Storage:TrainingMaterialsRequestPath"];


            if (string.IsNullOrWhiteSpace(requestPath))
            {
                requestPath = "/uploads/training-materials";

            }


            requestPath = requestPath.TrimEnd('/');



            var fileUrl = $"{requestPath}/{fileName}";


            // ---------------------------------------------
            // Create material record
            // ---------------------------------------------

            var createDto =
                new CreateTrainingMaterialDto
                {
                    FileUrl =
                        fileUrl,

                    FileType =
                        dto.FileType,

                    LessonId =
                        dto.LessonId,

                    UploadedByUserId =
                        dto.UploadedByUserId
                };


            var result =
                await _service.CreateAsync(
                    createDto,
                    dto.UploadedByUserId
                );


            return CreatedAtAction(
                nameof(GetDownloadUrl),
                new
                {
                    id = result.MaterialId
                },
                result
            );
        }


        // =====================================================
        // UPDATE TRAINING MATERIAL
        // PUT: api/TrainingMaterial/{id}
        // =====================================================

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(
            int id,
            UpdateTrainingMaterialDto dto)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }


            var updated =
                await _service.UpdateAsync(
                    id,
                    dto
                );


            if (!updated)
            {
                return NotFound();
            }


            return NoContent();
        }


        // =====================================================
        // DELETE TRAINING MATERIAL
        // DELETE: api/TrainingMaterial/{id}
        // =====================================================

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(
            int id)
        {
            var deleted =
                await _service.DeleteAsync(
                    id
                );


            if (!deleted)
            {
                return NotFound();
            }


            return NoContent();
        }


        // =====================================================
        // GET DOWNLOAD URL
        // GET: api/TrainingMaterial/{id}/download
        // =====================================================

        [HttpGet("{id}/download")]
        public async Task<IActionResult> GetDownloadUrl(
            int id)
        {
            var url =
                await _service.GetDownloadUrlAsync(
                    id
                );


            if (url == null)
            {
                return NotFound();
            }


            return Ok(
                new
                {
                    DownloadUrl = url
                }
            );
        }
    }
}