// <auto-generated>
// Implemented by Nora (Team 3 - Division 2: Identity, Organizations & People)
// </auto-generated>

namespace Nafadh_Backend.DTOs
{
  
    public class RoleDetailDTO
    {
        public int RoleId { get; set; }
        public string RoleName { get; set; } = string.Empty;
        public List<PermissionDTO> Permissions { get; set; } = new();
    }
}
