// <auto-generated>
// Implemented by Nora (Team 3 - Division 2: Identity, Organizations & People)
// </auto-generated>

namespace Nafadh_Backend.DTOs
{
    /// <summary>
    /// Response for POST /api/User/login - the access token plus enough profile
    /// data for the client to decide which portal shell to render.
    /// </summary>
    public class UserLoginResponseDTO
    {
        public string Token { get; set; } = string.Empty;
        public DateTime ExpiresAtUtc { get; set; }
        public int UserId { get; set; }
        public string FullName { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;
        public int RoleId { get; set; }
        public string RoleName { get; set; } = string.Empty;
    }
}
