// <auto-generated>
// Implemented by Nora (Team 3 - Division 2: Identity, Organizations & People)
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using Nafadh_Backend.Enums;

namespace Nafadh_Backend.DTOs
{
    /// <summary>
    /// Payload for PUT /api/User/{id}/status - activate/suspend/deactivate a user.
    /// </summary>
    public class UserStatusUpdateDTO
    {
        [Required]
        [EnumDataType(typeof(NFD_UserStatus))]
        public NFD_UserStatus Status { get; set; }
    }
}
