import { Component, OnInit, inject, signal } from '@angular/core';
import { DatePipe } from '@angular/common';

import { CompanyApi } from '../../services/company-api';
import { AuthService } from '../../../../core/auth/auth.service';
import { CompanyAccountDto } from '../../../../core/models/dtos';

type AccountTab = 'info' | 'permissions' | 'activities';

@Component({
  selector: 'app-my-account',
  imports: [DatePipe],
  templateUrl: './my-account.html',
  styleUrls: ['./my-account.scss'],
})
export class CompanyMyAccount implements OnInit {
  // ============================================================
  // Services
  // ============================================================

  private readonly api = inject(CompanyApi);

  readonly auth = inject(AuthService);


  // ============================================================
  // State
  // ============================================================

  profile = signal<CompanyAccountDto | null>(null);

  loading = signal(true);

  loadError = signal(false);

  activeTab = signal<AccountTab>('info');


  // ============================================================
  // Lifecycle
  // ============================================================

  ngOnInit(): void {
    this.loadAccount();
  }


  // ============================================================
  // Tabs
  // ============================================================

  setActiveTab(tab: AccountTab): void {
    this.activeTab.set(tab);
  }


  // ============================================================
  // Load Account
  // ============================================================

  loadAccount(): void {
    this.loading.set(true);
    this.loadError.set(false);

    this.api.getCurrentAccount().subscribe({
      next: (data) => {
        this.profile.set(data);
        this.loading.set(false);
      },

      error: (error) => {
        console.error(
          'Failed to load company account:',
          error
        );

        this.profile.set(null);
        this.loadError.set(true);
        this.loading.set(false);
      },
    });
  }


  // ============================================================
  // Export Account PDF
  // ============================================================
  //
  // IMPORTANT:
  // The PDF is now generated by the BACKEND.
  //
  // Frontend does NOT:
  // - use html2pdf
  // - use html2canvas
  // - convert HTML to image
  // - generate the PDF
  //
  // Instead:
  //
  // Angular
  //    ↓
  // CompanyApi
  //    ↓
  // GET /api/CompanyAccount/me/pdf
  //    ↓
  // ASP.NET Backend
  //    ↓
  // Database
  //    ↓
  // QuestPDF
  //    ↓
  // PDF Blob
  //    ↓
  // Browser Download
  //
  // ============================================================

  exportToPdf(): void {
    this.api.downloadMyAccountPdf().subscribe({
      next: (blob: Blob) => {
        if (!blob || blob.size === 0) {
          console.error(
            'The backend returned an empty PDF.'
          );

          return;
        }

        // Create temporary URL for the PDF
        const url = window.URL.createObjectURL(blob);

        // Create download link
        const link = document.createElement('a');

        link.href = url;

        link.download =
          `بيانات_الحساب_${this.getCurrentDateForFileName()}.pdf`;

        // Add link temporarily to DOM
        document.body.appendChild(link);

        // Start download
        link.click();

        // Clean up
        document.body.removeChild(link);

        window.URL.revokeObjectURL(url);
      },

      error: (error) => {
        console.error(
          'Failed to download account PDF:',
          error
        );
      },
    });
  }


  // ============================================================
  // PDF File Date
  // ============================================================

  private getCurrentDateForFileName(): string {
    const now = new Date();

    const year = now.getFullYear();

    const month = String(
      now.getMonth() + 1
    ).padStart(2, '0');

    const day = String(
      now.getDate()
    ).padStart(2, '0');

    return `${year}-${month}-${day}`;
  }
}
