
using Microsoft.EntityFrameworkCore;
using Nafadh_Backend.Models;
// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

namespace Nafadh_Backend.Repositories
{
    public class BatchTrainerRepository : IBatchTrainerRepository
    {
        private readonly Nafadhcontext _context;

        public BatchTrainerRepository(Nafadhcontext context)
        {
            _context = context;
        }

        public async Task<List<NFD_BatchTrainer>> GetByBatchIdAsync(int batchId)
        {
            return await _context.NFD_BatchTrainers
                .Where(bt => bt.BatchId == batchId)
                .ToListAsync();
        }

        public async Task<List<NFD_BatchTrainer>> GetByTrainerIdAsync(int trainerId)
        {
            return await _context.NFD_BatchTrainers
                .Where(bt => bt.TrainerId == trainerId)
                .ToListAsync();
        }

        public async Task<bool> ExistsAsync(int batchId, int trainerId)
        {
            return await _context.NFD_BatchTrainers
                .AnyAsync(bt => bt.BatchId == batchId && bt.TrainerId == trainerId);
        }

        public async Task<NFD_BatchTrainer> AddAsync(NFD_BatchTrainer entity)
        {
            _context.NFD_BatchTrainers.Add(entity);
            await _context.SaveChangesAsync();
            return entity;
        }

        public async Task<bool> DeleteAsync(int batchId, int trainerId)
        {
            var entity = await _context.NFD_BatchTrainers
                .FirstOrDefaultAsync(bt => bt.BatchId == batchId && bt.TrainerId == trainerId);

            if (entity == null) return false;

            _context.NFD_BatchTrainers.Remove(entity);
            await _context.SaveChangesAsync();
            return true;
        }
    }
}
