// <auto-generated>
// Added as part of Nafadh backend upgrade (Phase 2 - Contract Alignment).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;

namespace Nafadh_Backend.Repositories
{
    // Operates on the extended NFD_SupportTicket (as Conversation) and
    // NFD_Message (as threaded replies via TicketId) — see NFD_SupportTicket's
    // class-level comment. The original ticket-only usage via
    // SupportTicketController/ISupportTicketRepository is untouched.
    public class ConversationRepository : IConversationRepository
    {
        private readonly Nafadhcontext _context;

        public ConversationRepository(Nafadhcontext context)
        {
            _context = context;
        }

        public async Task<List<NFD_SupportTicket>> GetAsync(NFD_ConversationType? type, int? participantUserId, NFD_SupportTicketStatus? status)
        {
            var query = _context.NFD_SupportTickets
                .Include(t => t.User)
                .Include(t => t.Messages)
                .AsQueryable();

            if (type.HasValue)
                query = query.Where(t => t.Type == type.Value);

            if (participantUserId.HasValue)
                query = query.Where(t => t.UserId == participantUserId.Value
                    || t.Messages.Any(m => m.SenderId == participantUserId.Value));

            if (status.HasValue)
                query = query.Where(t => t.Status == status.Value);

            return await query
                .OrderByDescending(t => t.Messages.Any() ? t.Messages.Max(m => m.SentDate) : t.CreatedAt)
                .ToListAsync();
        }

        public async Task<NFD_SupportTicket?> GetByIdAsync(int conversationId)
        {
            return await _context.NFD_SupportTickets
                .Include(t => t.User)
                .Include(t => t.Messages)
                    .ThenInclude(m => m.Sender)
                .FirstOrDefaultAsync(t => t.TicketId == conversationId);
        }

        public async Task<NFD_SupportTicket> CreateAsync(NFD_SupportTicket conversation, NFD_Message firstMessage)
        {
            await _context.NFD_SupportTickets.AddAsync(conversation);
            await _context.SaveChangesAsync();

            firstMessage.TicketId = conversation.TicketId;
            await _context.NFD_Messages.AddAsync(firstMessage);
            await _context.SaveChangesAsync();

            return conversation;
        }

        public async Task<NFD_Message> AddMessageAsync(NFD_Message message)
        {
            await _context.NFD_Messages.AddAsync(message);
            await _context.SaveChangesAsync();
            return message;
        }

        public async Task UpdateStatusAsync(int conversationId, NFD_SupportTicketStatus status)
        {
            var conversation = await _context.NFD_SupportTickets.FindAsync(conversationId);
            if (conversation == null)
                throw new Exception("Conversation not found.");

            conversation.Status = status;
            await _context.SaveChangesAsync();
        }
    }
}
