// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// </auto-generated>
#nullable enable

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Nafadh_Backend.Interfaces;
using Nafadh_Backend.Models;
using Nafadh_Backend.Enums; // التأكد من استدعاء الـ Enums

namespace Nafadh_Backend.Repositories
{
    public class DepartmentRepository : IDepartmentRepository
    {
        private readonly Nafadhcontext _context;

        public DepartmentRepository(Nafadhcontext context)
        {
            _context = context;
        }


        //1-
        public async Task<IEnumerable<NFD_Department>> GetByCompanyIdAsync(int companyId)
        {
            return await _context.Set<NFD_Department>()
                .Where(d => d.CompanyId == companyId)
                .ToListAsync();
        }


        //2-
        public async Task<NFD_Department?> GetByIdAsync(int id)
        {
            return await _context.Set<NFD_Department>().FindAsync(id);
        }


        //3-
        public async Task AddAsync(NFD_Department department)
        {
            await _context.Set<NFD_Department>().AddAsync(department);
            await _context.SaveChangesAsync();
        }

        //4-

        public async Task UpdateAsync(NFD_Department department)
        {
            _context.Set<NFD_Department>().Update(department);
            await _context.SaveChangesAsync();
        }


        //5-
        public async Task DeleteAsync(NFD_Department department)
        {
            _context.Set<NFD_Department>().Remove(department);
            await _context.SaveChangesAsync();
        }

        //6-
        //
        public async Task<object> GetDepartmentPerformanceAsync(int departmentId)
        {
            var enrollments = await _context.Set<NFD_Enrollment>()
                .Where(e => e.DepartmentId == departmentId)
                .ToListAsync();

            return new
            {
                DepartmentId = departmentId,
                TotalEnrollments = enrollments.Count,
                CompletedCount = enrollments.Count(e => e.CompletionStatus.ToString() == "Completed")
            };
        }
    }
}