// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;
using Microsoft.EntityFrameworkCore;

namespace Nafadh_Backend.Repositories
{
    public class ExcuseRepository : IExcuseRepository
    {
        private readonly Nafadhcontext _context;

        public ExcuseRepository(Nafadhcontext context)
        {
            _context = context;
        }

        // جلب عذر واحد مرتبط بسجل حضور يومي معين.
        public async Task<NFD_Excuse?> GetByDailyAttendanceIdAsync(int dailyAttendanceId)
        {
            NFD_Excuse? result = await _context.NFD_Excuses
                .FirstOrDefaultAsync(e => e.DailyAttendanceId == dailyAttendanceId);
            return result;
        }

        // جلب عذر محدد عن طريق معرف العذر (Primary Key).
        public async Task<NFD_Excuse?> GetByIdAsync(int id)
        {
            NFD_Excuse? result = await _context.NFD_Excuses
                .FirstOrDefaultAsync(e => e.ExcuseId == id);
            return result;
        }

        // إضافة عذر جديد وإعادة الكائن المُضاف بعد حفظ التغييرات في قاعدة البيانات.
        public async Task<NFD_Excuse> AddAsync(NFD_Excuse entity)
        {
            await _context.NFD_Excuses.AddAsync(entity);
            await _context.SaveChangesAsync();
            return entity;
        }

        // تحديث بيانات عذر موجود سابقاً (مثل تغيير حالته أو تفاصيله) وحفظ التغييرات.
        public async Task UpdateAsync(NFD_Excuse entity)
        {
            _context.NFD_Excuses.Update(entity);
            await _context.SaveChangesAsync();
        }

        // جلب قائمة بجميع الأعذار التي ما زالت قيد الانتظار (Pending) ولم يتم البت فيها بعد.
        public async Task<List<NFD_Excuse>> GetPendingAsync()
        {
            List<NFD_Excuse> result = await _context.NFD_Excuses
                .Where(e => e.Status == NFD_ExcuseStatus.Pending)
                .ToListAsync();
            return result;
        }

    }
}