// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;

namespace Nafadh_Backend.Repositories
{
    public interface ICompanyRepository
    {
        // Get Company by ID
        Task<NFD_Company?> GetCompanyByIdAsync(int companyId);

        // Get all companies
        Task<IEnumerable<NFD_Company>> GetAllCompaniesAsync();

        // Get companies filtered by status and/or work field
        Task<IEnumerable<NFD_Company>> GetCompaniesAsync(
            NFD_CompanyStatus? status,
            string? workField);

        // Add a new company
        Task AddCompanyAsync(NFD_Company company);

        // Update an existing company
        Task UpdateCompanyAsync(NFD_Company company);

        // Delete a company by ID
        Task DeleteCompanyAsync(int companyId);
    }
}