// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.Models;

namespace Nafadh_Backend.Repositories
{
    public interface ICompanyPaymentRepository
    {
        Task<IEnumerable<NFD_CompanyPayment>> GetByCompanyIdAsync(int companyId);

        Task<NFD_CompanyPayment?> GetByIdAsync(int id);

        Task AddAsync(NFD_CompanyPayment payment);

        Task UpdateAsync(NFD_CompanyPayment payment);

      
    }
}