// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;

namespace Nafadh_Backend.Repositories
{
    public interface IEvaluationTemplateRepository
    {
        // TODO: define data-access contract methods for this entity
        Task<List<NFD_EvaluationTemplate>> GetTemplatesAsync(NFD_EvaluationType? type);

        // NEW: filter by module/stage — lets a trainer fetch "the criteria set
        // for Module X, Stage N" directly.
        Task<List<NFD_EvaluationTemplate>> GetTemplatesAsync(NFD_EvaluationType? type, int? moduleId, int? stage);

        Task<NFD_EvaluationTemplate?> GetTemplateByIdAsync(int templateId);

        Task AddTemplateAsync(NFD_EvaluationTemplate template);

        Task UpdateTemplateAsync(NFD_EvaluationTemplate template);

        Task DeleteTemplateAsync(NFD_EvaluationTemplate template);
    }
}