// <auto-generated>
// Added as part of Nafadh backend upgrade (Phase 2 - Contract Alignment).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;

namespace Nafadh_Backend.Repositories
{
    public interface IFeedbackRepository
    {
        Task<List<NFD_FeedbackCriterion>> GetCriteriaAsync(NFD_FeedbackType? appliesTo);

        Task<NFD_Feedback> AddFeedbackAsync(NFD_Feedback feedback);

        Task<List<NFD_Feedback>> GetByTrainerAsync(int trainerId);

        Task<List<NFD_Feedback>> GetByBatchAsync(int batchId);

        // Whether this trainee has already submitted the given feedback type for
        // this module (used by the "pending" trigger check).
        Task<bool> HasSubmittedAsync(int traineeId, int moduleId, NFD_FeedbackType type);
    }
}
