// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.DTOs;
using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;

namespace Nafadh_Backend.Repositories
{
    public interface IReportRepository
    {
        // TODO: define data-access contract methods for this entity
        Task<List<NFD_Report>> GetReportsAsync(NFD_ReportType? type, int? userId);
        Task AddReportAsync(NFD_Report report);
        Task<NFD_Report?> GetReportByIdAsync(int reportId);

        // NEW: analytics/aggregation queries — see DTOs/ReportAnalyticsDTOs.cs
        Task<DTOs.DashboardChartsDTO> GetDashboardChartsAsync();
        Task<BatchPerformanceReportDTO?> GetBatchPerformanceAsync(int batchId, int pageNumber, int pageSize);
        Task<DTOs.AttendanceReportDTO?> GetCompanyAttendanceReportAsync(int companyId);
        Task<List<DTOs.ChartPointDTO>> GetCompanyAttendanceChartAsync(int companyId);
        Task<List<DTOs.ChartPointDTO>> GetCompanyProgramDistributionAsync(int companyId);
        Task<List<int>> GetCompanyTopPerformerTraineeIdsAsync(int companyId, int take);
        Task<List<int>> GetCompanyAtRiskTraineeIdsAsync(int companyId, int take);
        Task<DTOs.TrainerKpisDTO> GetTrainerKpisAsync(int trainerId);

        Task<List<DTOs.TrainerTraineesReportRowDto>> GetTrainerTraineesReportRowsAsync(
    int trainerId,
    int? batchId
);
    }
}