// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.Models;

namespace Nafadh_Backend.Repositories
{
    public interface ISessionRepository
    {
        Task<List<NFD_Session>> GetAllAsync(int? batchId, int? trainerId, DateTime? date);
        Task<NFD_Session?> GetByIdAsync(int id);
        Task<List<NFD_Session>> GetByBatchIdAsync(int batchId);
        Task<NFD_Session> AddAsync(NFD_Session session);
        Task UpdateAsync(NFD_Session session);
        Task DeleteAsync(int id);
    }
}