// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.Models;

namespace Nafadh_Backend.Repositories
{
    public interface ISystemSettingRepository
    {
        Task<List<NFD_SystemSetting>> GetAllSystemSettingsAsync();

        Task<NFD_SystemSetting?> GetSystemSettingByKeyAsync(string key);

        Task AddSystemSettingAsync(NFD_SystemSetting systemSetting);

        Task UpdateSystemSettingAsync(NFD_SystemSetting systemSetting);

        Task DeleteSystemSettingAsync(NFD_SystemSetting systemSetting);
    }
}