// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.Models;

namespace Nafadh_Backend.Repositories
{
    public interface ITraineePaymentScheduleRepository
    {
        Task<IEnumerable<NFD_TraineePaymentSchedule>>
            GetByPaymentIdAsync(int traineePaymentId);



        Task AddRangeAsync(
            IEnumerable<NFD_TraineePaymentSchedule> schedules);



        Task<NFD_TraineePaymentSchedule?>
            GetByIdAsync(int id);



        Task UpdateAsync(
            NFD_TraineePaymentSchedule schedule);



        Task<IEnumerable<NFD_TraineePaymentSchedule>>
            GetOverdueAsync();
    }
}