// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;

namespace Nafadh_Backend.Repositories
{
    public interface ITraineeRepository
    {
        Task<(List<NFD_Trainee> Items, int TotalCount)> GetAllAsync(
            int? companyId, NFD_TraineeStatus? status, string? university, string? searchTerm,
            int pageNumber, int pageSize);

        Task<NFD_Trainee?> GetByIdAsync(int id);

        Task<NFD_Trainee?> GetByIdWithDashboardDataAsync(int id);

        Task<bool> UserHasTraineeProfileAsync(int userId);

        Task<bool> CompanyExistsAsync(int companyId);

        // NEW: trainees pending identity verification
        Task<List<NFD_Trainee>> GetPendingVerificationAsync();

        Task AddAsync(NFD_Trainee trainee);

        Task AddRangeAsync(IEnumerable<NFD_Trainee> trainees);

        void Update(NFD_Trainee trainee);

        Task<bool> SaveChangesAsync();
    }
}