// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Nafadh_Backend.Models;

namespace Nafadh_Backend.Repositories
{
    public interface IUserRepository
    {
        // TODO: define data-access contract methods for this entity
    }
}