#nullable enable

// <auto-generated>
// Generated as part of Nafadh backend scaffolding (Phase 1 - Database Design).
// Domain-owning teams may extend business logic in Services; Models/DbContext define the schema contract.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Nafadh_Backend.Enums;
using Nafadh_Backend.Models;

namespace Nafadh_Backend.Repositories
{
    public class WarningRepository : IWarningRepository
    {
        private readonly Nafadhcontext _context;

        public WarningRepository(Nafadhcontext context)
        {
            _context = context;
        }

        // Get all warnings for a specific enrollment
        // GET /api/Warning/enrollment/{enrollmentId}
        public async Task<IEnumerable<NFD_Warning>> GetWarningsByEnrollmentAsync(
            int enrollmentId)
        {
            return await _context.NFD_Warnings
                .Include(w => w.Enrollment).ThenInclude(e => e!.Trainee).ThenInclude(t => t!.User)
                .Include(w => w.User)
                .Where(w => w.EnrollmentId == enrollmentId)
                .ToListAsync();
        }

        // NEW: generic filtered query, used by the Admin Communications hub and
        // by both Company and Trainee portals' warning views.
        public async Task<IEnumerable<NFD_Warning>> GetWarningsAsync(
            NFD_WarningScope? scope, int? companyId, int? enrollmentId, NFD_WarningStatus? status, NFD_WarningLevel? level)
        {
            var query = _context.NFD_Warnings
                .Include(w => w.Company)
                .Include(w => w.Enrollment).ThenInclude(e => e!.Trainee).ThenInclude(t => t!.User)
                .Include(w => w.User)
                .AsQueryable();

            if (scope.HasValue)
                query = query.Where(w => w.Scope == scope.Value);

            if (companyId.HasValue)
                query = query.Where(w => w.CompanyId == companyId.Value);

            if (enrollmentId.HasValue)
                query = query.Where(w => w.EnrollmentId == enrollmentId.Value);

            if (status.HasValue)
                query = query.Where(w => w.Status == status.Value);

            if (level.HasValue)
                query = query.Where(w => w.Level == level.Value);

            return await query.OrderByDescending(w => w.IssuedDate).ToListAsync();
        }

        // Get warning details by ID
        // GET /api/Warning/{id}
        public async Task<NFD_Warning?> GetWarningByIdAsync(
            int warningId)
        {
            return await _context.NFD_Warnings
                .Include(w => w.Company)
                .Include(w => w.Enrollment).ThenInclude(e => e!.Trainee).ThenInclude(t => t!.User)
                .Include(w => w.User)
                .FirstOrDefaultAsync(w => w.WarningId == warningId);
        }

        // Create a new warning
        // POST /api/Warning
        public async Task AddWarningAsync(
            NFD_Warning warning)
        {
            await _context.NFD_Warnings.AddAsync(warning);
            await _context.SaveChangesAsync();
        }

        // Update warning status
        // PUT /api/Warning/{id}/status
        public async Task UpdateWarningStatusAsync(
            int warningId,
            NFD_WarningStatus status)
        {
            var warning = await _context.NFD_Warnings
                .FindAsync(warningId);

            if (warning == null)
            {
                throw new Exception("Warning not found");
            }

            warning.Status = status;

            await _context.SaveChangesAsync();
        }

        // Resolve warning
        // PUT /api/Warning/{id}/resolve
        public async Task ResolveWarningAsync(
            int warningId,
            string resolution)
        {
            var warning = await _context.NFD_Warnings
                .FindAsync(warningId);

            if (warning == null)
            {
                throw new Exception("Warning not found");
            }

            warning.Resolution = resolution;
            warning.Status = NFD_WarningStatus.Resolved;

            await _context.SaveChangesAsync();
        }

        // Get warnings that are not resolved
        // GET /api/Warning/pending
        public async Task<IEnumerable<NFD_Warning>> GetPendingWarningsAsync()
        {
            return await _context.NFD_Warnings
                .Where(w => w.Status != NFD_WarningStatus.Resolved)
                .ToListAsync();
        }

        // Get warnings by level
        // GET /api/Warning/level/{level}
        public async Task<IEnumerable<NFD_Warning>> GetWarningsByLevelAsync(
            NFD_WarningLevel level)
        {
            return await _context.NFD_Warnings
                .Where(w => w.Level == level)
                .ToListAsync();
        }
    }
}
